load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "keycloakfake",
    testonly = True,
    srcs = ["keycloakfake.go"],
    importpath = "github.com/whale-net/everything/libs/go/grpcauth/internal/keycloakfake",
    visibility = ["//libs/go/grpcauth:__subpackages__"],
    deps = [
        "@com_github_go_jose_go_jose_v4//:go-jose",
    ],
)
