"""flash_firmware() — board-aware, universal flash target macro.

Usage:

    load("//tools/firmware:flash.bzl", "flash_firmware")
    load("//tools/firmware/esp32:flash_config.bzl", "ESP32_DIO_80M")

    flash_firmware(
        name = "flash",
        firmware_name = "blink",          # name passed to esp32_firmware()
        board_config = ESP32_DIO_80M,
    )

Then:
    bazel run //demo/blink:flash -- /dev/ttyUSB0

For new CPU families, define an analogous struct in
tools/firmware/<family>/flash_config.bzl and pass it here.  The flash.py
driver supports: esptool (ESP32), avrdude (AVR), picotool (RP2040).
"""

load("@bazel_skylib//rules:write_file.bzl", "write_file")

# Runfile path to the shared flash.py driver.
_FLASH_PY_RUNFILE = "_main/tools/firmware/flash/flash.py"

def _label_to_runfile(label):
    """Convert a //pkg:target or :target label to a _main-workspace runfile path."""
    if label.startswith("//"):
        colon = label.find(":")
        if colon >= 0:
            pkg = label[2:colon]
            target = label[colon + 1:]
        else:
            pkg = label[2:]
            target = pkg.split("/")[-1]
        return "_main/{}/{}".format(pkg, target)
    elif label.startswith(":"):
        return "_main/{}/{}".format(native.package_name(), label[1:])
    return label

def flash_firmware(name, firmware_name, board_config, tags = None, visibility = None):
    """Create a 'bazel run' target that flashes a firmware binary to a board.

    Args:
        name:          Target name, typically "flash".
        firmware_name: The name passed to esp32_firmware() / firmware_binary().
                       Used to locate <firmware_name>.bin in the package.
        board_config:  A flash config struct (e.g. ESP32_DIO_80M from
                       //tools/firmware/esp32:flash_config.bzl).
        tags:          Extra tags; "manual" is always added automatically.
        visibility:    Target visibility.
    """
    if tags == None:
        tags = []
    if "manual" not in tags:
        tags = tags + ["manual"]

    pkg = native.package_name()
    binary_runfile = "_main/{}/{}.bin".format(pkg, firmware_name)

    # ── Build the generated wrapper script ────────────────────────────────────

    lines = [
        "#!/bin/bash",
        "# Generated by flash_firmware() — do not edit.",
        "set -euo pipefail",
        "",
        "# Bazel runfiles library bootstrap (v3)",
        "# shellcheck disable=SC1090",
        "f=bazel_tools/tools/bash/runfiles/runfiles.bash",
        # fmt: disable
        'source "${RUNFILES_DIR:-/dev/null}/$f" 2>/dev/null \\',
        '  || source "$(grep -sm1 "^$f " "${RUNFILES_MANIFEST_FILE:-/dev/null}" | cut -f2- -d" ")" 2>/dev/null \\',
        '  || source "$0.runfiles/$f" 2>/dev/null \\',
        '  || { echo >&2 "ERROR: cannot find $f"; exit 1; }',
        "unset f",
        "",
        'PORT="${1:-/dev/ttyUSB0}"',
        "",
        'FLASH_PY="$(rlocation ' + _FLASH_PY_RUNFILE + ')"',
        'APP_BIN="$(rlocation ' + binary_runfile + ')"',
    ]

    tool = board_config.tool

    if tool == "esptool":
        lines += [
            'ESPTOOL="$(rlocation ' + board_config.esptool_runfile + ')"',
        ]
        for _addr, runfile_path in board_config.pre_segments:
            var = "SEG_" + _addr.replace("0x", "x").upper()
            lines.append('{}="$(rlocation {})"'.format(var, runfile_path))

        lines += [
            "",
            'exec python3 "$FLASH_PY" \\',
            '    --port "$PORT" \\',
            "    --tool esptool \\",
            "    --chip {} \\".format(board_config.chip),
            "    --baud {} \\".format(board_config.baud),
            "    --before {} \\".format(board_config.before),
            "    --after {} \\".format(board_config.after),
            '    --write-flash-args "{}" \\'.format(board_config.write_flash_args),
        ]

        for addr, _runfile in board_config.pre_segments:
            var = "SEG_" + addr.replace("0x", "x").upper()
            lines.append('    --segment "{}=${}" \\'.format(addr, var))

        lines += [
            '    --segment "{}=$APP_BIN" \\'.format(board_config.app_offset),
            '    --esptool "$ESPTOOL"',
        ]

    elif tool == "avrdude":
        lines += [
            "",
            'exec python3 "$FLASH_PY" \\',
            '    --port "$PORT" \\',
            "    --tool avrdude \\",
            "    --part {} \\".format(getattr(board_config, "part", "m328p")),
            "    --programmer {} \\".format(getattr(board_config, "programmer", "arduino")),
            '    --segment "{}=$APP_BIN"'.format(board_config.app_offset),
        ]

    elif tool == "picotool":
        lines += [
            "",
            'exec python3 "$FLASH_PY" \\',
            '    --tool picotool \\',
            '    --segment "{}=$APP_BIN"'.format(board_config.app_offset),
        ]

    else:
        fail("flash_firmware: unknown tool '{}'. Supported: esptool, avrdude, picotool".format(tool))

    wrapper_name = name + "_wrapper.sh"
    write_file(
        name = name + "_wrapper_gen",
        out = wrapper_name,
        content = lines,
        is_executable = True,
    )

    # ── Assemble data deps ────────────────────────────────────────────────────

    data = [
        "//tools/firmware/flash:flash.py",
        ":" + firmware_name + "_bin",
    ]
    if tool == "esptool":
        data += [board_config.esptool] + list(board_config.pre_segment_labels)

    native.sh_binary(
        name = name,
        srcs = [wrapper_name],
        data = data,
        deps = ["@bazel_tools//tools/bash/runfiles"],
        tags = tags,
        visibility = visibility,
    )
