"""flash_firmware() — board-aware, universal flash target macro.

Usage:

    load("//tools/firmware:flash.bzl", "flash_firmware")
    load("//tools/firmware/esp32:flash_config.bzl", "ESP32_DIO_80M")

    flash_firmware(
        name = "flash",
        firmware_name = "blink",          # name passed to esp32_firmware()
        board_config = ESP32_DIO_80M,
    )

Then:
    bazel run //demo/blink:flash -- /dev/ttyUSB0

For new CPU families, define an analogous struct in
tools/firmware/<family>/flash_config.bzl and pass it here.  The flash.py
driver supports: esptool (ESP32), avrdude (AVR), picotool (RP2040).
"""

load("@bazel_skylib//rules:write_file.bzl", "write_file")

# _main is the canonical workspace name for the root module under bzlmod.
# It is a Bazel constant — not a project-specific choice.
_WORKSPACE = "_main"

def _runfile_path(label, output):
    """Compute the rlocation path for a generated output file.

    Args:
        label:  Bazel label string, e.g. "//tools/firmware/esp32:foo_bin"
        output: Output filename, e.g. "foo.bin"

    Returns:
        rlocation-relative path, e.g. "_main/tools/firmware/esp32/foo.bin"
    """
    pkg = label.lstrip("/").split(":")[0]  # "tools/firmware/esp32"
    return "{}/{}/{}".format(_WORKSPACE, pkg, output)

# Runfile path to the shared flash.py driver (source file in py_binary data).
_FLASH_PY_RUNFILE = _runfile_path("//tools/firmware/flash:flash.py", "flash.py")

# ── Exec-hosted tool wrapper ─────────────────────────────────────────────────
# When building with a cross-compiled target platform (e.g. --config=esp32),
# Bazel builds all `data` deps in the target configuration. Flash tools like
# esptool run on the developer's host machine, so they must be built in the
# exec (host) configuration. This rule wraps a py_binary with cfg="exec" and
# exposes its runfiles so rlocation() in the flash script finds the binary at
# its original workspace-relative path.

def _exec_hosted_tool_impl(ctx):
    tool = ctx.attr.tool[DefaultInfo]
    return [DefaultInfo(
        files = tool.files,
        runfiles = tool.default_runfiles,
    )]

_exec_hosted_tool = rule(
    implementation = _exec_hosted_tool_impl,
    attrs = {
        "tool": attr.label(
            cfg = "exec",
            executable = True,
            mandatory = True,
        ),
    },
)

def flash_firmware(name, firmware_name, board_config, tags = None, visibility = None):
    """Create a 'bazel run' target that flashes a firmware binary to a board.

    Args:
        name:          Target name, typically "flash".
        firmware_name: The name passed to esp32_firmware() / firmware_binary().
                       Used to locate <firmware_name>.bin in the package.
        board_config:  A flash config struct (e.g. ESP32_DIO_80M from
                       //tools/firmware/esp32:flash_config.bzl).
        tags:          Extra tags; "manual" is always added automatically.
        visibility:    Target visibility.
    """
    if tags == None:
        tags = []
    if "manual" not in tags:
        tags = tags + ["manual"]

    pkg = native.package_name()
    binary_runfile = "_main/{}/{}.bin".format(pkg, firmware_name)

    # ── Build the generated wrapper script ────────────────────────────────────

    lines = [
        "#!/bin/bash",
        "# Generated by flash_firmware() — do not edit.",
        "set -euo pipefail",
        "",
        "# Bazel runfiles library bootstrap (v3)",
        "# shellcheck disable=SC1090",
        "f=bazel_tools/tools/bash/runfiles/runfiles.bash",
        # fmt: disable
        'source "${RUNFILES_DIR:-/dev/null}/$f" 2>/dev/null \\',
        '  || source "$(grep -sm1 "^$f " "${RUNFILES_MANIFEST_FILE:-/dev/null}" | cut -f2- -d" ")" 2>/dev/null \\',
        '  || source "$0.runfiles/$f" 2>/dev/null \\',
        '  || { echo >&2 "ERROR: cannot find $f"; exit 1; }',
        "unset f",
        "",
        'PORT="${1:-/dev/ttyUSB0}"',
        "",
        'FLASH_PY="$(rlocation ' + _FLASH_PY_RUNFILE + ')"',
        'APP_BIN="$(rlocation ' + binary_runfile + ')"',
    ]

    tool = board_config.tool

    if tool == "esptool":
        esptool_label = board_config.esptool
        # esptool is a py_binary; its binary name matches the target name.
        esptool_target = esptool_label.split(":")[-1]
        esptool_runfile = _runfile_path(esptool_label, esptool_target)
        lines += [
            'ESPTOOL="$(rlocation ' + esptool_runfile + ')"',
        ]
        for seg in board_config.pre_segments:
            var = "SEG_" + seg.addr.replace("0x", "x").upper()
            lines.append('{}="$(rlocation {})"'.format(
                var,
                _runfile_path(seg.label, seg.output),
            ))

        lines += [
            "",
            'exec python3 "$FLASH_PY" \\',
            '    --port "$PORT" \\',
            "    --tool esptool \\",
            "    --chip {} \\".format(board_config.chip),
            "    --baud {} \\".format(board_config.baud),
            "    --before {} \\".format(board_config.before),
            "    --after {} \\".format(board_config.after),
            '    --write-flash-args "{}" \\'.format(board_config.write_flash_args),
        ]

        for seg in board_config.pre_segments:
            var = "SEG_" + seg.addr.replace("0x", "x").upper()
            lines.append('    --segment "{}=${}" \\'.format(seg.addr, var))

        lines += [
            '    --segment "{}=$APP_BIN" \\'.format(board_config.app_offset),
            '    --esptool "$ESPTOOL"',
        ]

    elif tool == "avrdude":
        lines += [
            "",
            'exec python3 "$FLASH_PY" \\',
            '    --port "$PORT" \\',
            "    --tool avrdude \\",
            "    --part {} \\".format(getattr(board_config, "part", "m328p")),
            "    --programmer {} \\".format(getattr(board_config, "programmer", "arduino")),
            '    --segment "{}=$APP_BIN"'.format(board_config.app_offset),
        ]

    elif tool == "picotool":
        lines += [
            "",
            'exec python3 "$FLASH_PY" \\',
            '    --tool picotool \\',
            '    --segment "{}=$APP_BIN"'.format(board_config.app_offset),
        ]

    else:
        fail("flash_firmware: unknown tool '{}'. Supported: esptool, avrdude, picotool".format(tool))

    wrapper_name = name + "_wrapper.sh"
    write_file(
        name = name + "_wrapper_gen",
        out = wrapper_name,
        content = lines,
        is_executable = True,
    )

    # ── Assemble data deps ────────────────────────────────────────────────────

    data = [
        "//tools/firmware/flash:flash.py",
        ":" + firmware_name + "_bin",
    ]
    if tool == "esptool":
        # Wrap esptool in an exec-cfg target so it is always built for the host
        # platform, not the embedded target platform (e.g. ESP32 / os:none).
        exec_tool_name = "_" + name + "_esptool_exec"
        _exec_hosted_tool(
            name = exec_tool_name,
            tool = board_config.esptool,
            tags = tags,
            visibility = ["//visibility:private"],
        )
        data += [":" + exec_tool_name] + [seg.label for seg in board_config.pre_segments]

    native.sh_binary(
        name = name,
        srcs = [wrapper_name],
        data = data,
        deps = ["@bazel_tools//tools/bash/runfiles"],
        tags = tags,
        visibility = visibility,
    )
