"""board_pins() — generate a type-safe, board-specific pin header at build time.

Usage (in a board's BUILD.bazel):

    load("//tools/firmware:pins.bzl", "board_pins")

    board_pins(
        name = "my_board_pins",
        board_name = "my_board",
        pins = {
            "Led":  2,
            "Sda": 21,
            "Scl": 22,
        },
    )

Application code:

    #include "board_pins.h"   // resolves via //tools/firmware:board_pins alias
    // C macros:    BOARD_PIN_LED, BOARD_PIN_SDA, BOARD_PIN_SCL
    //              BOARD_PIN_SDA_SUPPORTED  (1 if wired, 0 if absent on this board)
    // C++ constants: board::kLed, board::kSda, board::kScl

Pin schema
----------
REQUIRED_PINS: Every board must declare these. board_pins() fails at analysis
               time if any are missing.

OPTIONAL_PINS: Boards may omit these. Absent pins default to -1 and get a
               BOARD_PIN_X_SUPPORTED = 0 flag so firmware can guard cleanly:

                   #if BOARD_PIN_SDA_SUPPORTED
                       Wire.begin(board::kSda, board::kScl);
                   #endif

               Add names here whenever a new optional peripheral pin is
               introduced anywhere in the firmware.

Registration
------------
Use board_pins_registry() in tools/firmware/BUILD.bazel instead of a raw
alias() + select(). Every new board gets one entry there.
"""

load("@bazel_skylib//rules:write_file.bzl", "write_file")

# ── Pin schema ────────────────────────────────────────────────────────────────

# Every board must declare all of these. board_pins() fails at analysis time
# if any are absent.
REQUIRED_PINS = [
    "Led",  # onboard indicator LED
]

# Boards may omit any of these; omitted pins default to -1 with _SUPPORTED = 0.
# Add new names here when introducing a new peripheral pin in any firmware.
OPTIONAL_PINS = [
    "Sda",    # I2C data
    "Scl",    # I2C clock
    "Rx2",    # UART2 RX
    "Tx2",    # UART2 TX
    "Adc0",   # primary analog input (e.g. thermistor voltage divider)
]

# ── board_pins() ──────────────────────────────────────────────────────────────

def board_pins(name, board_name, pins, visibility = None):
    """Generate a cc_library that exposes board-specific pin constants.

    The output header is always named 'board_pins.h' and is includable as:
        #include "board_pins.h"

    board_pins() enforces the pin schema at Bazel analysis time:
    - Required pins (REQUIRED_PINS) must be present; missing ones cause fail().
    - Optional pins (OPTIONAL_PINS) default to -1 if absent.

    NOTE: Each call must be in its own Bazel package. Two board_pins() calls
    in the same BUILD.bazel will collide on the 'board_pins.h' output filename.

    Args:
        name:       cc_library target name (e.g. "elegoo_esp32_pins").
        board_name: human-readable board label used in the file comment.
        pins:       dict of PascalCase logical name -> GPIO pin number (int).
                    Negative values mean "not connected / not available".
        visibility: target visibility; defaults to public.
    """
    if visibility == None:
        visibility = ["//visibility:public"]

    # ── Validate required pins ────────────────────────────────────────────────
    for required in REQUIRED_PINS:
        if required not in pins:
            fail(
                "board_pins({name}): missing required pin '{pin}'. " +
                "Every board must declare all REQUIRED_PINS ({all}). " +
                "Add '{pin}' to the pins dict (use -1 if not wired).".format(
                    name = board_name,
                    pin = required,
                    all = ", ".join(REQUIRED_PINS),
                ),
            )

    # ── Merge optional pins (absent = -1) ─────────────────────────────────────
    # Build a canonical ordered dict: required first, then optional, then extras.
    merged = {}
    for p in REQUIRED_PINS:
        merged[p] = pins[p]
    for p in OPTIONAL_PINS:
        merged[p] = pins.get(p, -1)
    # Pass through any board-specific pins not in the schema unchanged.
    for p, v in pins.items():
        if p not in merged:
            merged[p] = v

    # ── Generate header ───────────────────────────────────────────────────────
    lines = [
        "// Generated by board_pins() — do not edit manually.",
        "// Board: " + board_name,
        "#pragma once",
        "",
        "// C-compatible macros.",
        "// For optional pins: BOARD_PIN_<NAME>_SUPPORTED is 1 if wired, 0 if absent.",
    ]

    for pin_name, pin_num in merged.items():
        upper = pin_name.upper()
        is_optional = pin_name in OPTIONAL_PINS
        if is_optional:
            supported = "1" if pin_num >= 0 else "0"
            lines.append("#define BOARD_PIN_{upper}_SUPPORTED  {s}".format(
                upper = upper,
                s = supported,
            ))
        lines.append("#define BOARD_PIN_{upper}  {num}".format(
            upper = upper,
            num = pin_num,
        ))

    lines += [
        "",
        "#ifdef __cplusplus",
        "namespace board {",
    ]

    for pin_name, pin_num in merged.items():
        lines.append(
            "inline constexpr int k{name} = {num};".format(
                name = pin_name,
                num = pin_num,
            ),
        )

    lines += [
        "}  // namespace board",
        "#endif  // __cplusplus",
        "",
    ]

    # Output into a per-board subdirectory so two board_pins() calls in the
    # same package don't clobber each other's board_pins.h.
    out_hdr = name + "/board_pins.h"

    write_file(
        name = name + "_hdr",
        out = out_hdr,
        content = lines,
    )

    native.cc_library(
        name = name,
        hdrs = [out_hdr],
        # includes = [name] adds <pkg>/<name>/ to the search path so that
        # `#include "board_pins.h"` resolves the generated file without the
        # caller needing to know the board subdirectory.
        includes = [name],
        visibility = visibility,
    )

# ── board_pins_registry() ─────────────────────────────────────────────────────

def board_pins_registry(name, boards, visibility = None):
    """Create the board_pins alias from a dict of config_setting → pins target.

    Use this in tools/firmware/BUILD.bazel instead of a raw alias() + select().
    Every new board adds exactly one entry to the boards dict.

    Args:
        name:       alias target name (conventionally "board_pins").
        boards:     dict of {config_setting_label: pins_library_label}.
                    e.g. {"//tools/firmware/esp32:is_elegoo_esp32":
                              "//tools/firmware/esp32:elegoo_esp32_pins"}
        visibility: target visibility; defaults to public.
    """
    if visibility == None:
        visibility = ["//visibility:public"]

    select_map = {}
    for config_setting, pins_target in boards.items():
        select_map[config_setting] = pins_target
    select_map["//conditions:default"] = ":no_board_pins"

    native.alias(
        name = name,
        actual = select(select_map),
        visibility = visibility,
    )
