load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "fake",
    srcs = [
        "fake.go",
        "reconcile.go",
    ],
    importpath = "github.com/whale-net/everything/tools/app_registry/server/repository/fake",
    visibility = ["//visibility:public"],
    deps = [
        "//tools/app_registry/server/repository",
        "//tools/appmeta/proto:appmetapb",
        "@com_github_google_uuid//:uuid",
    ],
)
