load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "cmd",
    srcs = [
        "apps.go",
        "artifacts.go",
        "builds.go",
        "client.go",
        "env.go",
        "promote.go",
        "root.go",
        "util.go",
    ],
    importpath = "github.com/whale-net/everything/tools/app_registry/cli/cmd",
    visibility = ["//visibility:public"],
    deps = [
        "//libs/go/grpcauth",
        "//libs/go/grpcclient",
        "//tools/app_registry/apierrors",
        "//tools/app_registry/protos:appregistrypb",
        "//tools/appmeta/proto:appmetapb",
        "@com_github_google_uuid//:uuid",
        "@com_github_spf13_cobra//:cobra",
        "@org_golang_google_genproto_googleapis_rpc//errdetails",
        "@org_golang_google_grpc//status",
        "@org_golang_google_protobuf//encoding/protojson",
        "@org_golang_google_protobuf//proto",
    ],
)

go_test(
    name = "cmd_test",
    srcs = [
        "builds_test.go",
        "promote_test.go",
        "root_test.go",
    ],
    embed = [":cmd"],
    deps = [
        "//tools/app_registry/apierrors",
        "//tools/app_registry/protos:appregistrypb",
        "@org_golang_google_genproto_googleapis_rpc//errdetails",
        "@org_golang_google_grpc//codes",
        "@org_golang_google_grpc//status",
    ],
)
