-- No-op placeholder. ui_sessions now lives in libs/go/htmxauth's bundled
-- migration (version 900001), merged into this domain's sequence via
-- migrate.WithSource in migrate/main.go -- see that package's migrations.go
-- for why (avoiding copy-pasted schema SQL across every htmxauth adopter).
--
-- This file is kept (rather than deleted) only to hold open version slot
-- 012, since postgres_integration_*_test.go steps through this domain's
-- migrations by ordinal position (e.g. Steps(14) to reach migration 014)
-- and deleting a slot would silently shift every later Steps(N) checkpoint.
