package grpcauth

import (
	"context"
	"crypto/subtle"
	"errors"
	"fmt"
	"log/slog"
	"time"

	jose "github.com/go-jose/go-jose/v4"
	"github.com/go-jose/go-jose/v4/jwt"
	"golang.org/x/oauth2"
)

// pendingAuthorizationTTL bounds how long a PendingAuthorization returned by
// BeginAuthorization may be completed. A flow older than this is rejected by
// CompleteAuthorization without attempting a token exchange, so an
// indefinitely-lived browser session (or a replayed old callback) cannot
// resurrect a stale flow.
const pendingAuthorizationTTL = 10 * time.Minute

// Authorization-leg errors (FR1, FR2, FR11, NFR3, NFR5). Like the sentinels
// in granterrors.go, callers must branch on these with errors.Is and never
// on the error string.
var (
	// ErrAuthorizationStateMismatch is returned when the callback's state
	// does not exactly match the state BeginAuthorization generated for this
	// flow (or either is empty). No token exchange is attempted (NFR5).
	ErrAuthorizationStateMismatch = errors.New("grpcauth: authorization callback state mismatch")

	// ErrAuthorizationExpired is returned when CompleteAuthorization is
	// called with a PendingAuthorization older than pendingAuthorizationTTL.
	// No token exchange is attempted.
	ErrAuthorizationExpired = errors.New("grpcauth: authorization flow expired")

	// ErrAuthorizationSubjectMismatch is returned when the identity in the
	// token obtained from the exchange does not match the subject the flow
	// was started for. Nothing is persisted (NFR3): a grant belonging to one
	// subject can never be established under another subject's key.
	ErrAuthorizationSubjectMismatch = errors.New("grpcauth: authorization callback identity does not match requested subject")

	// ErrAuthorizationNoRefreshToken is returned when the token endpoint's
	// response carries no refresh_token, meaning offline_access was
	// requested but not actually granted -- almost always a Keycloak client
	// misconfiguration (the "Offline Access" client scope not assigned, or
	// consent not actually completed). See KEYCLOAK.md § "Delegated grants
	// (offline_access)".
	ErrAuthorizationNoRefreshToken = errors.New("grpcauth: token response included no refresh token -- check that the Keycloak client has the \"Offline Access\" client scope and offline_access was actually granted (see KEYCLOAK.md § Delegated grants)")
)

// PendingAuthorization is the caller-visible state of one in-flight
// authorization-code + PKCE consent flow, returned by BeginAuthorization and
// handed back (verbatim, from wherever the caller stored it -- a cookie, a
// server-side session) to CompleteAuthorization once the browser returns
// from Keycloak.
//
// grpcauth does not own session storage: persisting a PendingAuthorization
// across the redirect is the caller's responsibility.
type PendingAuthorization struct {
	// Subject and Grant are the (subject, grant) key this flow will persist
	// under once it completes (FR2).
	Subject, Grant string

	// State is the per-flow CSRF token generated by BeginAuthorization
	// (NFR5). The caller must bind it to the initiating browser session and
	// compare it to the callback's own state -- CompleteAuthorization does
	// this comparison itself using the State carried here, so the caller
	// only needs to round-trip this struct.
	State string

	// CodeVerifier is the PKCE code_verifier generated by BeginAuthorization.
	// Never logged -- see String()/LogValue() (NFR1).
	CodeVerifier string

	// CreatedAt is when BeginAuthorization created this flow. Used by
	// CompleteAuthorization to reject a flow older than
	// pendingAuthorizationTTL.
	CreatedAt time.Time
}

// String redacts CodeVerifier so an accidental %v/%s of a
// PendingAuthorization (in a log line or error) cannot leak PKCE secret
// material (NFR1).
func (p PendingAuthorization) String() string {
	return fmt.Sprintf(
		"PendingAuthorization{Subject:%q Grant:%q State:%q CodeVerifier:%s CreatedAt:%s}",
		p.Subject, p.Grant, p.State, redactedPlaceholder(p.CodeVerifier), p.CreatedAt,
	)
}

// LogValue implements slog.LogValuer so slog.Any("pending", p) (or an
// accidental %v inside a structured log call) redacts CodeVerifier the same
// way String() does (NFR1).
func (p PendingAuthorization) LogValue() slog.Value {
	return slog.StringValue(p.String())
}

// BeginAuthorization starts a one-time browser consent flow for
// (subject, grant): a fresh per-flow CSRF state (NFR5) and PKCE verifier/
// challenge pair are generated, and the returned authURL is the Keycloak
// authorization endpoint URL to redirect the browser to.
//
// The caller must persist the returned PendingAuthorization against the
// initiating browser session (cookie, server-side session store -- grpcauth
// does not own this) and hand it back to CompleteAuthorization along with
// the callback's state and code.
//
// redirect_uri is always s.cfg.RedirectURI: there is no parameter here for a
// caller (or, transitively, a request) to supply a different one (NFR5).
func (s *DelegatedGrantSource) BeginAuthorization(ctx context.Context, subject, grant string) (authURL string, pending PendingAuthorization, err error) {
	if subject == "" {
		return "", PendingAuthorization{}, errors.New("grpcauth: BeginAuthorization: subject is required")
	}
	if grant == "" {
		return "", PendingAuthorization{}, errors.New("grpcauth: BeginAuthorization: grant is required")
	}

	state, err := randomURLSafeToken()
	if err != nil {
		return "", PendingAuthorization{}, fmt.Errorf("grpcauth: generate authorization state: %w", err)
	}

	verifier, err := generatePKCEVerifier()
	if err != nil {
		return "", PendingAuthorization{}, fmt.Errorf("grpcauth: generate PKCE verifier: %w", err)
	}
	challenge := pkceChallengeS256(verifier)

	authURL = s.oauth2Cfg.AuthCodeURL(
		state,
		oauth2.SetAuthURLParam("code_challenge", challenge),
		oauth2.SetAuthURLParam("code_challenge_method", "S256"),
	)

	return authURL, PendingAuthorization{
		Subject:      subject,
		Grant:        grant,
		State:        state,
		CodeVerifier: verifier,
		CreatedAt:    time.Now(),
	}, nil
}

// CompleteAuthorization finishes the consent flow started by
// BeginAuthorization: it verifies the callback against pending, exchanges
// code at Keycloak's token endpoint using pending.CodeVerifier (PKCE),
// checks the resulting identity against pending.Subject, and persists the
// refresh token via Store.Persist.
//
// Re-running this for an existing (subject, grant) -- e.g. after
// Store.MarkNeedsReauth -- is the re-authorization path (FR11): Persist
// overwrites the existing row under the same key rather than creating a new
// grant identity.
func (s *DelegatedGrantSource) CompleteAuthorization(ctx context.Context, pending PendingAuthorization, callbackState, code string) error {
	// 1. Constant-time state comparison (NFR5). A mismatch -- including
	// either side being empty -- fails closed before any network call.
	if !statesMatch(pending.State, callbackState) {
		return ErrAuthorizationStateMismatch
	}

	// 2. A pending flow does not live forever: an old, unused flow (or a
	// replayed callback for one) cannot be completed.
	if time.Since(pending.CreatedAt) > pendingAuthorizationTTL {
		return ErrAuthorizationExpired
	}

	// 3. Exchange at Endpoints.Token as a confidential client (FR14):
	// s.oauth2Cfg carries ClientID+ClientSecret, so oauth2.Config.Exchange
	// authenticates the request itself. redirect_uri is s.cfg.RedirectURI
	// (from s.oauth2Cfg.RedirectURL), never anything caller-supplied
	// (NFR5).
	token, err := s.oauth2Cfg.Exchange(ctx, code, oauth2.SetAuthURLParam("code_verifier", pending.CodeVerifier))
	if err != nil {
		return fmt.Errorf("grpcauth: exchange authorization code: %w", err)
	}

	// 4. The identity the exchange authenticated must be the subject this
	// flow was started for -- never persisted under a mismatched subject
	// (NFR3).
	subject, err := subjectFromAccessToken(token.AccessToken)
	if err != nil {
		return fmt.Errorf("grpcauth: read access token subject: %w", err)
	}
	if subject != pending.Subject {
		return ErrAuthorizationSubjectMismatch
	}

	// 5. offline_access must actually have been granted.
	if token.RefreshToken == "" {
		return ErrAuthorizationNoRefreshToken
	}

	// 6. Persist overwrites any existing material for (subject, grant) and
	// resets status to active (Store contract, store.go) -- this is what
	// makes re-running consent for a needs_reauth grant the re-authorization
	// path (FR11) rather than a new grant identity.
	if err := s.cfg.Store.Persist(ctx, pending.Subject, pending.Grant, TokenMaterial{
		RefreshToken: token.RefreshToken,
		ObtainedAt:   time.Now(),
	}); err != nil {
		return fmt.Errorf("grpcauth: persist delegated grant: %w", err)
	}

	return nil
}

// statesMatch reports whether callbackState is exactly pending, compared in
// constant time so a timing side channel cannot help an attacker guess the
// state (NFR5). Either side being empty is always a mismatch: an
// unpopulated PendingAuthorization.State (a caller bug) must not be
// satisfiable by an equally-empty callback state.
func statesMatch(pending, callbackState string) bool {
	if pending == "" || callbackState == "" {
		return false
	}
	if len(pending) != len(callbackState) {
		return false
	}
	return subtle.ConstantTimeCompare([]byte(pending), []byte(callbackState)) == 1
}

// jwtSignatureAlgorithms is the set of algorithms subjectFromAccessToken
// will parse. Keycloak's default realm signing key is RS256; ES256 is what
// internal/keycloakfake signs with for these tests. Both (plus the other
// common RSA/EC/PS families) are accepted since this package never verifies
// the signature -- see subjectFromAccessToken -- so there is no security
// reason to restrict which algorithm merely *parses*.
var jwtSignatureAlgorithms = []jose.SignatureAlgorithm{
	jose.RS256, jose.RS384, jose.RS512,
	jose.ES256, jose.ES384, jose.ES512,
	jose.PS256, jose.PS384, jose.PS512,
}

// subjectFromAccessToken extracts the `sub` claim from a Keycloak access
// token JWT.
//
// This deliberately does not verify the token's signature. The access token
// is not being used here as a bearer credential presented by an untrusted
// party -- it is the direct response body of a token-endpoint call this
// package itself made, over TLS, authenticated with the confidential
// client's own secret (FR14). Verifying the signature would only re-prove
// what that authenticated channel already established, at the cost of a
// JWKS fetch this package has no other need for. Do not reuse this helper
// for a token arriving over an untrusted path (e.g. from a caller's
// Authorization header) -- that is auth.go's oidcVerifier, which does
// verify.
func subjectFromAccessToken(accessToken string) (string, error) {
	tok, err := jwt.ParseSigned(accessToken, jwtSignatureAlgorithms)
	if err != nil {
		return "", fmt.Errorf("parse access token: %w", err)
	}

	var claims jwt.Claims
	if err := tok.UnsafeClaimsWithoutVerification(&claims); err != nil {
		return "", fmt.Errorf("read access token claims: %w", err)
	}
	if claims.Subject == "" {
		return "", errors.New("access token has no sub claim")
	}
	return claims.Subject, nil
}
