load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "repository",
    srcs = [
        "models.go",
        "promotability.go",
        "repository.go",
        "watermark.go",
    ],
    importpath = "github.com/whale-net/everything/tools/app_registry/server/repository",
    visibility = ["//visibility:public"],
    deps = [
        "//tools/appmeta/proto:appmetapb",
    ],
)

go_test(
    name = "repository_test",
    srcs = ["promotability_test.go"],
    embed = [":repository"],
    deps = [
        "//tools/appmeta/proto:appmetapb",
    ],
)
