load("@rules_python//python:defs.bzl", "py_library")
load("//tools/bazel:pytest.bzl", "py_test")

py_library(
    name = "logging",
    srcs = [
        "__init__.py",
        "config.py",
        "context.py",
        "factory.py",
        "formatters.py",
        "metrics.py",
        "otel_handler.py",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "@pypi//:opentelemetry-api",
        "@pypi//:opentelemetry-exporter-otlp",
        "@pypi//:opentelemetry-sdk",
    ],
)

py_test(
    name = "config_test",
    size = "small",
    srcs = ["config_test.py"],
    deps = [":logging"],
)
