name: 'Setup Build Environment'
description: 'Sets up Bazel, Python, Go, and Docker for CI/CD workflows'
branding:
  icon: 'settings'
  color: 'green'

inputs:
  setup-docker:
    description: 'Whether to setup Docker Buildx'
    required: false
    default: 'false'
  cache-suffix:
    description: 'Suffix to add to cache keys for isolation'
    required: false
    default: ''

outputs:
  bazel-cache-hit:
    description: 'Whether Bazel cache was hit'
    value: ${{ steps.setup-bazel.outputs.cache-hit }}

runs:
  using: composite
  steps:
    - name: Setup Remote Cache Environment
      shell: bash
      run: |
        # Configure remote cache if URL is provided via secrets
        if [[ -n "$BAZEL_REMOTE_CACHE_URL" ]]; then
          echo "Setting up Bazel remote cache..."
          
          # Set the remote cache URL from secret
          CACHE_URL="$BAZEL_REMOTE_CACHE_URL"
          
          # Add basic auth credentials if provided via secrets
          if [[ -n "$BAZEL_REMOTE_CACHE_USER" && -n "$BAZEL_REMOTE_CACHE_PASSWORD" ]]; then
            # Extract protocol and host from URL
            PROTOCOL=$(echo "$CACHE_URL" | sed -n 's#^\([^:]*\)://.*#\1#p')
            HOST_PATH=$(echo "$CACHE_URL" | sed -n 's#^[^:]*://\(.*\)#\1#p')
            
            # Construct URL with basic auth
            CACHE_URL="${PROTOCOL}://${BAZEL_REMOTE_CACHE_USER}:${BAZEL_REMOTE_CACHE_PASSWORD}@${HOST_PATH}"
          fi
          
          # Create .bazelrc.remote file with remote cache configuration
          cat > .bazelrc.remote << EOF
        # Remote cache configuration (auto-generated)
        build --remote_cache=${CACHE_URL}
        build --remote_upload_local_results=true
        build:ci --remote_cache=${CACHE_URL}
        build:ci --remote_upload_local_results=true
        EOF
          
          echo "✅ Remote cache configured at: $BAZEL_REMOTE_CACHE_URL"
        else
          echo "No remote cache URL provided, using local caching only"
          # Remove any existing .bazelrc.remote file to ensure clean state
          rm -f .bazelrc.remote
        fi
      env:
        BAZEL_REMOTE_CACHE_URL: ${{ secrets.BAZEL_REMOTE_CACHE_URL }}
        BAZEL_REMOTE_CACHE_USER: ${{ secrets.BAZEL_REMOTE_CACHE_USER }}
        BAZEL_REMOTE_CACHE_PASSWORD: ${{ secrets.BAZEL_REMOTE_CACHE_PASSWORD }}

    - name: Setup Bazel with Multi-Layered Caching
      id: setup-bazel
      uses: bazel-contrib/setup-bazel@0.15.0
      with:
        # Enable global caching for Bazel binaries and dependencies
        bazelisk-cache: true
        repository-cache: true
        # Simple disk cache - isolated by cache suffix
        disk-cache: ${{ inputs.cache-suffix || 'true' }}

    - name: Set up Docker Buildx
      if: ${{ inputs.setup-docker == 'true' }}
      uses: docker/setup-buildx-action@v3