load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "rmqtest",
    srcs = ["rmqtest.go"],
    importpath = "github.com/whale-net/everything/libs/go/rmqtest",
    visibility = ["//visibility:public"],
    deps = [
        "//libs/go/rmq",
        "@com_github_testcontainers_testcontainers_go//:testcontainers-go",
        "@com_github_testcontainers_testcontainers_go//wait",
    ],
)
