package cmd

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/spf13/cobra"
)

// HelmChartMetadata is the JSON structure generated by the helm_chart_metadata Bazel rule.
type HelmChartMetadata struct {
	Name        string   `json:"name"`
	Domain      string   `json:"domain"`
	Namespace   string   `json:"namespace"`
	Apps        []string `json:"apps"`
	ChartTarget string   `json:"chart_target"`
	BazelTarget string   `json:"-"`
}

func helmChartMetadataFilePath(workspaceRoot, targetLabel string) (string, error) {
	if !strings.HasPrefix(targetLabel, "//") {
		return "", fmt.Errorf("invalid bazel target: %q", targetLabel)
	}
	parts := strings.SplitN(targetLabel[2:], ":", 2)
	if len(parts) != 2 {
		return "", fmt.Errorf("invalid bazel target (missing colon): %q", targetLabel)
	}
	pkg, name := parts[0], parts[1]
	return filepath.Join(workspaceRoot, "bazel-bin", pkg, name+"_chart_metadata.json"), nil
}

func GetHelmChartMetadata(targetLabel string, bazel BazelRunner, fs FileSystem, workspaceRoot string) (HelmChartMetadata, error) {
	if _, err := bazel.Run("build", targetLabel); err != nil {
		return HelmChartMetadata{}, fmt.Errorf("bazel build %s: %w", targetLabel, err)
	}
	path, err := helmChartMetadataFilePath(workspaceRoot, targetLabel)
	if err != nil {
		return HelmChartMetadata{}, err
	}
	data, err := fs.ReadFile(path)
	if err != nil {
		return HelmChartMetadata{}, fmt.Errorf("read %s: %w", path, err)
	}
	var m HelmChartMetadata
	if err := json.Unmarshal(data, &m); err != nil {
		return HelmChartMetadata{}, fmt.Errorf("parse %s: %w", path, err)
	}
	m.BazelTarget = targetLabel
	return m, nil
}

// helmChartMetadataStarlarkExpr extracts helm chart metadata in one cquery
// call by reading the HelmChartMetadataInfo provider.
const helmChartMetadataStarlarkExpr = `str(target.label) + "\t" + json.encode(providers(target)["//tools/bazel:release.bzl%HelmChartMetadataInfo"].metadata)`

// ListAllHelmCharts mirrors ListAllApps: a loading-phase query lists targets
// so cquery analysis can be scoped, keeping discovery robust to unrelated
// analysis failures elsewhere in `//...`.
func ListAllHelmCharts(bazel BazelRunner, _ FileSystem, _ string) ([]HelmChartMetadata, error) {
	labelsOut, err := bazel.Run("query", "kind(helm_chart_metadata, //...)", "--output=label")
	if err != nil {
		return nil, fmt.Errorf("bazel query helm_chart_metadata: %w", err)
	}
	labels := splitNonEmpty(labelsOut)
	if len(labels) == 0 {
		return nil, nil
	}

	// `--keep_going` for parity with ListAllApps: don't let an unrelated
	// analysis error block helm chart discovery.
	out, err := bazel.Run("cquery", strings.Join(labels, " + "), "--output=starlark",
		"--starlark:expr="+helmChartMetadataStarlarkExpr, "--keep_going")
	if err != nil && out == "" {
		return nil, fmt.Errorf("bazel cquery helm_chart_metadata: %w", err)
	}
	var charts []HelmChartMetadata
	for _, line := range strings.Split(out, "\n") {
		line = strings.TrimSpace(line)
		if line == "" {
			continue
		}
		label, jsonPart, ok := strings.Cut(line, "\t")
		if !ok {
			fmt.Fprintf(os.Stderr, "Warning: malformed cquery line: %q\n", line)
			continue
		}
		var m HelmChartMetadata
		if err := json.Unmarshal([]byte(jsonPart), &m); err != nil {
			fmt.Fprintf(os.Stderr, "Warning: parse helm metadata for %s: %v\n", label, err)
			continue
		}
		m.BazelTarget = canonicalLabel(label)
		charts = append(charts, m)
	}
	sort.Slice(charts, func(i, j int) bool { return charts[i].Name < charts[j].Name })
	return charts, nil
}

func newPlanHelmReleaseCmd() *cobra.Command {
	var (
		charts      string
		version     string
		format      string
		includeDemo bool
	)

	cmd := &cobra.Command{
		Use:          "plan-helm-release",
		Short:        "Plan a helm chart release and output CI matrix",
		SilenceUsage: true,
		RunE: func(cmd *cobra.Command, args []string) error {
			if format != "json" && format != "github" {
				fmt.Fprintf(cmd.ErrOrStderr(), "Error: format must be one of: json, github\n")
				return fmt.Errorf("invalid format")
			}

			workspaceRoot, err := defaultWorkspaceRoot()
			if err != nil {
				return fmt.Errorf("workspace root: %w", err)
			}

			allCharts, err := ListAllHelmCharts(defaultBazel, defaultFS, workspaceRoot)
			if err != nil {
				return err
			}

			selected := selectHelmCharts(charts, allCharts, includeDemo, cmd)

			effectiveVersion := version
			if effectiveVersion == "" {
				effectiveVersion = "0.1.0"
			}

			type matrixEntry struct {
				Chart   string `json:"chart"`
				Domain  string `json:"domain"`
				Version string `json:"version"`
			}
			var include []matrixEntry
			var chartNames []string
			for _, c := range selected {
				include = append(include, matrixEntry{Chart: c.Name, Domain: c.Domain, Version: effectiveVersion})
				chartNames = append(chartNames, c.Name)
			}

			result := map[string]interface{}{
				"matrix": map[string]interface{}{"include": include},
				"charts": chartNames,
			}
			if include == nil {
				result["matrix"] = map[string]interface{}{"include": []matrixEntry{}}
				result["charts"] = []string{}
			}

			if format == "github" {
				matrixJSON, _ := json.Marshal(result["matrix"])
				fmt.Fprintf(cmd.OutOrStdout(), "matrix=%s\n", matrixJSON)
				fmt.Fprintf(cmd.OutOrStdout(), "charts=%s\n", strings.Join(chartNames, " "))
				return nil
			}

			out, _ := json.MarshalIndent(result, "", "  ")
			fmt.Fprintln(cmd.OutOrStdout(), string(out))
			return nil
		},
	}

	cmd.Flags().StringVar(&charts, "charts", "", "Comma-separated list of chart names, domain names, or 'all'")
	cmd.Flags().StringVar(&version, "version", "", "Release version for charts")
	cmd.Flags().StringVar(&format, "format", "json", "Output format (json or github)")
	cmd.Flags().BoolVar(&includeDemo, "include-demo", false, "Include demo domain charts when using 'all'")

	return cmd
}

func selectHelmCharts(input string, allCharts []HelmChartMetadata, includeDemo bool, cmd *cobra.Command) []HelmChartMetadata {
	if input == "" {
		return allCharts
	}
	chartInput := strings.TrimSpace(strings.ToLower(input))
	if chartInput == "all" {
		if includeDemo {
			return allCharts
		}
		fmt.Fprintln(cmd.ErrOrStderr(), "Excluding demo domain charts from 'all' (use --include-demo to include)")
		var result []HelmChartMetadata
		for _, c := range allCharts {
			if c.Domain != "demo" {
				result = append(result, c)
			}
		}
		return result
	}

	requested := strings.Split(chartInput, ",")
	seen := map[string]bool{}
	var result []HelmChartMetadata
	for _, req := range requested {
		req = strings.TrimSpace(req)
		for _, c := range allCharts {
			if (c.Name == req || c.Domain == req) && !seen[c.Name] {
				seen[c.Name] = true
				result = append(result, c)
			}
		}
	}
	return result
}
