{{- if .Values.podDisruptionBudget.enabled }}
{{- range $serviceName, $serviceConfig := .Values.services }}
{{- if $serviceConfig.enabled }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "manman.serviceFullName" (dict "serviceName" $serviceName "suffix" "pdb" "Values" $.Values) }}
  namespace: {{ $.Values.namespace }}
  labels:
    {{- include "manman.labels" $ | nindent 4 }}
    app: {{ include "manman.serviceName" (dict "serviceName" $serviceName "Values" $.Values) }}
    component: {{ $serviceConfig.component }}
    service-type: {{ $serviceConfig.type }}
spec:
  {{- if $.Values.podDisruptionBudget.minAvailable }}
  minAvailable: {{ $.Values.podDisruptionBudget.minAvailable }}
  {{- end }}
  {{- if $.Values.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ $.Values.podDisruptionBudget.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "manman.serviceSelectorLabels" (dict "serviceName" $serviceName "Values" $.Values) | nindent 6 }}
{{- end }}
{{- end }}
{{- end }}