// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/whale-net/everything/libs/go/htmxauth"

// MisconfigBanner is the FR-59 persistent misconfiguration banner. Shell
// renders it on every screen (see layout.templ) so it is never opt-in per
// page. It renders only when RolesMisconfigured(user) is true — i.e. the
// realm_access.roles claim was entirely absent from the token, almost
// always a missing Keycloak "Add to ID token" realm-roles mapper on the
// client scope — never for a legitimate present-but-empty roles claim
// (read-only viewer) and never under AUTH_MODE=none (see RolesMisconfigured
// doc comment for why that exemption falls out for free here).
//
// This must never be mistaken for a reason to stop serving read screens:
// callers keep rendering the rest of the page underneath the banner so an
// admin can still diagnose the problem instead of being locked out.
func MisconfigBanner(user *htmxauth.UserInfo) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		if RolesMisconfigured(user) {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div role=\"alert\" class=\"alert alert-error shadow-md\"><span class=\"font-semibold\">Roles claim missing from this session.</span> <span>The identity token has no realm_access.roles claim at all — this is almost always a Keycloak client scope missing the \"Add to ID token\" realm-roles mapper, not an intentional no-roles account. Read screens still work below, but every role-gated action is denied until this is fixed.</span></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
