load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "release",
    srcs = [
        "activities.go",
        "approval.go",
        "buildref.go",
        "finalize.go",
        "github.go",
        "plan.go",
        "record.go",
        "workflow.go",
    ],
    importpath = "github.com/whale-net/everything/tools/app_registry/worker/release",
    visibility = ["//visibility:public"],
    deps = [
        "//libs/go/s3",
        "//tools/app_registry/server/repository",
        "//tools/app_registry/worker/writeback",
        "@io_temporal_go_sdk//activity",
        "@io_temporal_go_sdk//temporal",
        "@io_temporal_go_sdk//workflow",
    ],
)

go_test(
    name = "release_test",
    srcs = [
        "activities_test.go",
        "buildref_test.go",
        "finalize_test.go",
        "github_test.go",
        "plan_test.go",
        "record_test.go",
        "workflow_test.go",
    ],
    embed = [":release"],
    deps = [
        "//tools/app_registry/server/repository",
        "//tools/app_registry/server/repository/fake",
        "//tools/app_registry/worker/writeback",
        "//tools/appmeta/proto:appmetapb",
        "@com_github_stretchr_testify//mock",
        "@com_github_stretchr_testify//require",
        "@io_temporal_go_sdk//activity",
        "@io_temporal_go_sdk//testsuite",
    ],
)
