// Package render implements FR13-FR15 (issue #2495): the one-way
// projection of a krill Product's current spec back out to the committed
// doc set -- `<domain>/PRODUCT.md` plus `<domain>/product/*.md`, the exact
// layout tools/project-manager/CONVENTIONS.md § Layout defines. It is the
// mirror image of krill/importer: importer only ever parses a committed
// doc into entities, this package only ever renders entities into a doc.
//
// FR15/LB5 -- one-way, structurally enforced: Render's only dependency on
// krill's data is the Source interface below, and every method on it is a
// read (a List or a Get). There is no Create, no Update, no method capable
// of writing to krill anywhere in this package's own dependency graph --
// nothing here holds a *store.Store, only the narrow read surface Source
// declares. StoreSource (store_source.go) is the adapter a caller wires up
// against a real *store.Store, but Render itself never sees that concrete
// type, only the interface. See render_integration_test.go's read-only-role
// test for the empirical proof: Render succeeds against a Postgres
// connection whose role has had every write privilege revoked.
//
// FR14 -- every numbered citation (`Cn`, `LBn`) this package renders is
// computed here, at render time, from each entity's position among its
// returned siblings (krill/store's queries already order by `position` then
// `name` -- see krill/store/models.go's package doc). Nothing in this
// package reads a stored display number, because no such column exists
// (LB2) -- see numberByOrder below.
package render

import (
	"context"
	"fmt"
	"regexp"
	"sort"
	"strconv"
	"strings"
	"time"

	"github.com/google/uuid"

	"github.com/whale-net/everything/krill/slice"
	"github.com/whale-net/everything/krill/store"
)

// Source is the read-only surface Render depends on (FR15). Every method
// is a read against krill's current (valid_to IS NULL) rows; there is no
// write method here for the same reason there is no *store.Store field
// anywhere in this package -- a caller cannot accidentally give Render a
// way to mutate krill even by mistake, because the type it is handed
// simply has no such method to call.
type Source interface {
	// GetProductSlice returns productID's whole-product slice (FR8) --
	// the Product itself, every FeatureSet, Feature, and
	// LoadBearingDecision beneath it. *slice.Querier satisfies this
	// directly.
	GetProductSlice(ctx context.Context, productID uuid.UUID) (slice.Document, error)

	// ListPersonas returns every current Persona under productID.
	ListPersonas(ctx context.Context, productID uuid.UUID) ([]store.Persona, error)

	// ListNonGoals returns every current NonGoal (both kinds) under
	// productID.
	ListNonGoals(ctx context.Context, productID uuid.UUID) ([]store.NonGoal, error)

	// ListMilestoneRefs returns every MilestoneRef under (scopeID,
	// productID) -- the bare `M<n>` identifiers a product's roadmap
	// names (LB6).
	ListMilestoneRefs(ctx context.Context, scopeID, productID uuid.UUID) ([]store.MilestoneRef, error)

	// ListMilestoneAssociations returns every EntityMilestone row for
	// milestoneID -- the rows a `Delivers:`/`Must not foreclose:` line is
	// reconstructed from (LB6), never stored prose.
	ListMilestoneAssociations(ctx context.Context, milestoneID uuid.UUID) ([]store.EntityMilestone, error)
}

// GeneratedMarker is the exact sentence NFR3's AGENTS.md carve-out and
// every generated file's own header both carry, so a contributor who opens
// a rendered file sees the same instruction a doc reader gets from
// AGENTS.md itself. Keep this string identical in both places -- it is
// grepped by test and by contributors deciding whether a file is safe to
// hand-edit.
const GeneratedMarker = "GENERATED by krill/render -- do not hand-edit; edit krill's entities and re-render instead"

// Files is the rendered four-file doc set (tools/project-manager/
// CONVENTIONS.md § Layout): PRODUCT.md is the index (Vision, Personas,
// Load-bearing decisions, Non-goals inline, per that section's own
// carve-out for short/stable/cross-referenced content); the other three
// split out because they have no natural ceiling.
type Files struct {
	ProductMD       string // <domain>/PRODUCT.md
	CurrentStateMD  string // <domain>/product/01-current-state.md
	CapabilityMapMD string // <domain>/product/02-capability-map.md
	RoadmapMD       string // <domain>/product/03-roadmap.md
}

// FileMap returns f as a map from the path each file is written at,
// relative to the domain's own root directory (e.g. "krill/" for krill
// itself) -- the shape krill/render/cmd writes to disk.
func (f Files) FileMap() map[string]string {
	return map[string]string{
		"PRODUCT.md":                   f.ProductMD,
		"product/01-current-state.md":  f.CurrentStateMD,
		"product/02-capability-map.md": f.CapabilityMapMD,
		"product/03-roadmap.md":        f.RoadmapMD,
	}
}

// Render assembles Files for productID by reading src alone (FR13, FR15).
// scopeID is productID's owning scope (LB1) -- needed to enumerate its
// milestone refs, which are keyed (scope, product, name) rather than by
// product alone (see migration 004's comment on why: two different
// products under the same scope may each have their own "M1").
func Render(ctx context.Context, src Source, scopeID, productID uuid.UUID) (Files, error) {
	doc, err := src.GetProductSlice(ctx, productID)
	if err != nil {
		return Files{}, fmt.Errorf("get product slice: %w", err)
	}
	if doc.Product == nil {
		return Files{}, fmt.Errorf("product %s: no current row (GetProductSlice returned an empty Product)", productID)
	}

	personas, err := src.ListPersonas(ctx, productID)
	if err != nil {
		return Files{}, fmt.Errorf("list personas: %w", err)
	}
	nonGoals, err := src.ListNonGoals(ctx, productID)
	if err != nil {
		return Files{}, fmt.Errorf("list non-goals: %w", err)
	}
	milestones, err := renderMilestones(ctx, src, scopeID, productID, doc)
	if err != nil {
		return Files{}, fmt.Errorf("assemble milestones: %w", err)
	}

	revision := doc.Product.RevisionID.String()
	name := doc.Product.Name

	return Files{
		ProductMD:       renderProductMD(name, revision, doc, personas, nonGoals),
		CurrentStateMD:  renderCurrentStateMD(name, revision),
		CapabilityMapMD: renderCapabilityMapMD(name, revision, doc),
		RoadmapMD:       renderRoadmapMD(name, revision, milestones),
	}, nil
}

// header is the provenance line every generated file carries (LB5): the
// entity this file was rendered from (a Product, by name and immutable
// id), the exact SCD2 revision it came from, and a render timestamp, plus
// NFR3's non-hand-editable marker. now is a parameter (not time.Now()
// called inline) so callers -- and this package's own tests -- get a
// deterministic header to assert against.
func header(productName, revisionID string, now time.Time) string {
	return fmt.Sprintf(
		"<!-- %s\n     Rendered by krill/render from Product %q, revision %s, at %s. -->\n",
		GeneratedMarker, productName, revisionID, now.UTC().Format(time.RFC3339))
}

// nowFunc is overridden in tests that need a fixed timestamp; production
// callers never need to touch it.
var nowFunc = time.Now

func renderProductMD(name, revision string, doc slice.Document, personas []store.Persona, nonGoals []store.NonGoal) string {
	var b strings.Builder

	b.WriteString(header(name, revision, nowFunc()))
	b.WriteString("\n# ")
	b.WriteString(name)
	b.WriteString(" — Product brief\n\n")
	b.WriteString("This file is the index. Vision, Personas, Load-bearing decisions, and Non-goals are inline; the three sections with no natural ceiling are split out (`tools/project-manager/CONVENTIONS.md` § Layout):\n\n")
	b.WriteString("| Section | File |\n|---|---|\n")
	b.WriteString("| Current state | [`product/01-current-state.md`](product/01-current-state.md) |\n")
	b.WriteString("| Capability map | [`product/02-capability-map.md`](product/02-capability-map.md) |\n")
	b.WriteString("| Roadmap | [`product/03-roadmap.md`](product/03-roadmap.md) |\n\n")

	b.WriteString("## Vision\n\n")
	b.WriteString(strings.TrimSpace(doc.Product.Vision))
	b.WriteString("\n\n")

	b.WriteString("## Personas\n\n")
	for _, p := range personas {
		b.WriteString("- **")
		b.WriteString(p.Name)
		b.WriteString("**")
		if p.Description != nil && strings.TrimSpace(*p.Description) != "" {
			b.WriteString(" — ")
			b.WriteString(strings.TrimSpace(*p.Description))
		}
		b.WriteString("\n")
	}
	b.WriteString("\n")

	b.WriteString("## Load-bearing decisions\n\n")
	decisionNumbers := numberByOrder(doc.Decisions, func(d slice.DecisionEntity) uuid.UUID { return d.ID })
	for _, d := range doc.Decisions {
		title := cleanDecisionTitle(d.Name)
		b.WriteString(fmt.Sprintf("LB%d — %s\n", decisionNumbers[d.ID], title))
		if d.Body != nil && strings.TrimSpace(*d.Body) != "" {
			b.WriteString(strings.TrimSpace(*d.Body))
			b.WriteString("\n")
		}
		b.WriteString("\n")
	}

	b.WriteString("## Non-goals\n\n")
	b.WriteString("**Permanent:**\n\n")
	for _, ng := range nonGoals {
		if ng.Kind != store.NonGoalKindPermanent {
			continue
		}
		writeNonGoalBullet(&b, ng)
	}
	b.WriteString("\n**Explicitly *not* non-goals — deferred, not foreclosed:**\n\n")
	for _, ng := range nonGoals {
		if ng.Kind != store.NonGoalKindDeferred {
			continue
		}
		writeNonGoalBullet(&b, ng)
	}

	return b.String()
}

func writeNonGoalBullet(b *strings.Builder, ng store.NonGoal) {
	b.WriteString("- **")
	b.WriteString(ng.Name)
	b.WriteString(".**")
	if ng.Body != nil && strings.TrimSpace(*ng.Body) != "" {
		b.WriteString(" ")
		b.WriteString(strings.TrimSpace(*ng.Body))
	}
	b.WriteString("\n")
}

// leadingLBLabelRe strips a leading "LB<n> — " (or "--"/"-") token from a
// stored LoadBearingDecision.Name -- krill/importer/parse.go's
// parseDecisions keeps the whole source title line (including its own
// `LBn —` prefix) as Name, so a decision imported as "LB1" carries that
// literal text in its stored Name forever, even after a later insert
// renumbers it to LB2 at render time (FR14). Rendering must never trust
// that embedded prefix as the citation -- only the freshly computed
// position does -- so this strips it before re-prefixing with the
// recomputed number.
var leadingLBLabelRe = regexp.MustCompile(`^LB\d+\s*[—–-]\s*`)

func cleanDecisionTitle(name string) string {
	return leadingLBLabelRe.ReplaceAllString(strings.TrimSpace(name), "")
}

func renderCurrentStateMD(name, revision string) string {
	var b strings.Builder
	b.WriteString(header(name, revision, nowFunc()))
	b.WriteString("\n# Current state\n\n")
	b.WriteString("_No entity in krill's model backs this section (see `krill/ARCHITECTURE.md` \"Capability map entries, personas, and non-goals\"); krill/render always emits this file as an empty placeholder so the four-file layout stays complete._\n")
	return b.String()
}

func renderCapabilityMapMD(name, revision string, doc slice.Document) string {
	var b strings.Builder
	b.WriteString(header(name, revision, nowFunc()))
	b.WriteString("\n# Capability map\n\n")

	featureNumbers := numberByOrder(doc.Features, func(f slice.FeatureEntity) uuid.UUID { return f.ID })

	// Group Features by their parent FeatureSet, in the order FeatureSets
	// and Features are both already returned (feature_set.position/name,
	// then feature.position/name -- krill/store/slice.go's
	// ListFeaturesByProduct query). A FeatureSet with no Features (e.g.
	// the importer's synthetic "Load-bearing decisions" holder) is
	// skipped entirely -- it has nothing to number.
	featuresBySet := map[uuid.UUID][]slice.FeatureEntity{}
	for _, f := range doc.Features {
		featuresBySet[f.FeatureSetID] = append(featuresBySet[f.FeatureSetID], f)
	}
	for _, fs := range doc.FeatureSets {
		features := featuresBySet[fs.ID]
		if len(features) == 0 {
			continue
		}
		b.WriteString("## ")
		b.WriteString(fs.Name)
		b.WriteString("\n\n")
		for _, f := range features {
			b.WriteString(fmt.Sprintf("- **C%d** — %s\n", featureNumbers[f.ID], f.Name))
		}
		b.WriteString("\n")
	}

	return b.String()
}

// milestoneEntry is one milestone's rendered content, reconstructed
// entirely from milestone_ref + entity_milestone rows (LB6) -- never
// authored prose. M1 ships no milestone title, outcome sentence, or FR
// budget (those are M3's, per krill/ARCHITECTURE.md's "milestone
// references" section), so this is deliberately thinner than a
// hand-authored roadmap entry.
type milestoneEntry struct {
	Number           int
	ID               string // "M1".."Mn"
	Delivers         []string
	MustNotForeclose []string
}

// milestoneNumRe extracts the numeric suffix of a bare "M<n>" identifier.
var milestoneNumRe = regexp.MustCompile(`^M(\d+)$`)

func renderMilestones(ctx context.Context, src Source, scopeID, productID uuid.UUID, doc slice.Document) ([]milestoneEntry, error) {
	refs, err := src.ListMilestoneRefs(ctx, scopeID, productID)
	if err != nil {
		return nil, fmt.Errorf("list milestone refs: %w", err)
	}
	if len(refs) == 0 {
		return nil, nil
	}

	featureNumbers := numberByOrder(doc.Features, func(f slice.FeatureEntity) uuid.UUID { return f.ID })
	decisionNumbers := numberByOrder(doc.Decisions, func(d slice.DecisionEntity) uuid.UUID { return d.ID })

	entries := make([]milestoneEntry, 0, len(refs))
	for _, ref := range refs {
		associations, err := src.ListMilestoneAssociations(ctx, ref.ID)
		if err != nil {
			return nil, fmt.Errorf("list associations for milestone %s: %w", ref.Name, err)
		}

		var delivers, mustNot []int
		for _, a := range associations {
			if n, ok := featureNumbers[a.EntityID]; ok {
				delivers = append(delivers, n)
				continue
			}
			if n, ok := decisionNumbers[a.EntityID]; ok {
				mustNot = append(mustNot, n)
			}
		}
		sort.Ints(delivers)
		sort.Ints(mustNot)

		num := 0
		if m := milestoneNumRe.FindStringSubmatch(ref.Name); m != nil {
			num, _ = strconv.Atoi(m[1])
		}
		entries = append(entries, milestoneEntry{
			Number:           num,
			ID:               ref.Name,
			Delivers:         prefixEach("C", delivers),
			MustNotForeclose: prefixEach("LB", mustNot),
		})
	}

	sort.Slice(entries, func(i, j int) bool { return entries[i].Number < entries[j].Number })
	return entries, nil
}

func prefixEach(prefix string, nums []int) []string {
	if len(nums) == 0 {
		return nil
	}
	out := make([]string, len(nums))
	for i, n := range nums {
		out[i] = fmt.Sprintf("%s%d", prefix, n)
	}
	return out
}

func renderRoadmapMD(name, revision string, milestones []milestoneEntry) string {
	var b strings.Builder
	b.WriteString(header(name, revision, nowFunc()))
	b.WriteString("\n# Roadmap\n\n")

	for _, m := range milestones {
		b.WriteString("### ")
		b.WriteString(m.ID)
		b.WriteString("\n\n")
		if len(m.Delivers) > 0 {
			b.WriteString("Delivers: ")
			b.WriteString(strings.Join(m.Delivers, ", "))
			b.WriteString("\n")
		}
		if len(m.MustNotForeclose) > 0 {
			b.WriteString("Must not foreclose: ")
			b.WriteString(strings.Join(m.MustNotForeclose, ", "))
			b.WriteString("\n")
		}
		b.WriteString("\n")
	}

	return b.String()
}

// numberByOrder assigns a 1-based display number to every element of
// entities in the order the slice already arrives in -- FR14's "computed
// at render time from the entity's current position among its siblings."
// krill/store's own queries already return Features and
// LoadBearingDecisions ordered by (position, name) (see
// krill/store/models.go's package doc and krill/store/slice.go's ORDER BY
// clauses), so the order this function numbers is exactly sibling order;
// nothing here reads or writes a stored column. Inserting a new sibling
// between two existing ones changes no id in krill/store and no entry of
// this map for an untouched sibling's identity -- only the *number* that
// entity resolves to next render.
func numberByOrder[T any](entities []T, idOf func(T) uuid.UUID) map[uuid.UUID]int {
	numbers := make(map[uuid.UUID]int, len(entities))
	for i, e := range entities {
		numbers[idOf(e)] = i + 1
	}
	return numbers
}
