load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "events",
    srcs = ["events.go"],
    importpath = "github.com/whale-net/everything/tools/app_registry/events",
    visibility = ["//visibility:public"],
    deps = [
        "@com_github_rabbitmq_amqp091_go//:amqp091-go",
    ],
)

go_test(
    name = "events_test",
    srcs = ["events_test.go"],
    embed = [":events"],
    deps = [
        "@com_github_rabbitmq_amqp091_go//:amqp091-go",
    ],
)
