"""add game server configuration models

Revision ID: 456f1ad094f4
Revises: ddda5d340ddd
Create Date: 2025-10-27 19:57:44.816432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '456f1ad094f4'
down_revision: Union[str, None] = 'ddda5d340ddd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_server_commands',
    sa.Column('game_server_command_id', sa.Integer(), nullable=False),
    sa.Column('game_server_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('command', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_visible', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['game_server_id'], ['manman.game_servers.game_server_id'], ),
    sa.PrimaryKeyConstraint('game_server_command_id'),
    schema='manman'
    )
    op.create_index(op.f('ix_manman_game_server_commands_game_server_id'), 'game_server_commands', ['game_server_id'], unique=False, schema='manman')
    op.create_index('ixu_game_server_commands_game_server_name', 'game_server_commands', ['game_server_id', 'name'], unique=True, schema='manman')
    op.create_table('game_server_command_defaults',
    sa.Column('game_server_command_default_id', sa.Integer(), nullable=False),
    sa.Column('game_server_command_id', sa.Integer(), nullable=False),
    sa.Column('command_value', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_visible', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['game_server_command_id'], ['manman.game_server_commands.game_server_command_id'], ),
    sa.PrimaryKeyConstraint('game_server_command_default_id'),
    schema='manman'
    )
    op.create_index(op.f('ix_manman_game_server_command_defaults_game_server_command_id'), 'game_server_command_defaults', ['game_server_command_id'], unique=False, schema='manman')
    op.create_table('game_server_config_commands',
    sa.Column('game_server_config_command_id', sa.Integer(), nullable=False),
    sa.Column('game_server_config_id', sa.Integer(), nullable=False),
    sa.Column('game_server_command_id', sa.Integer(), nullable=False),
    sa.Column('command_value', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_visible', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['game_server_command_id'], ['manman.game_server_commands.game_server_command_id'], ),
    sa.ForeignKeyConstraint(['game_server_config_id'], ['manman.game_server_configs.game_server_config_id'], ),
    sa.PrimaryKeyConstraint('game_server_config_command_id'),
    schema='manman'
    )
    op.create_index(op.f('ix_manman_game_server_config_commands_game_server_command_id'), 'game_server_config_commands', ['game_server_command_id'], unique=False, schema='manman')
    op.create_index(op.f('ix_manman_game_server_config_commands_game_server_config_id'), 'game_server_config_commands', ['game_server_config_id'], unique=False, schema='manman')
    op.create_index('ixu_game_server_config_commands_config_command', 'game_server_config_commands', ['game_server_config_id', 'game_server_command_id', 'command_value'], unique=True, schema='manman')
    op.create_table('game_server_config_options',
    sa.Column('game_server_config_option_id', sa.Integer(), nullable=False),
    sa.Column('game_server_config_id', sa.Integer(), nullable=False),
    sa.Column('option_type', sa.Enum('ARG', 'ENV_VAR', 'POST_INSTALL_SCRIPT', name='configoptiontype'), nullable=False),
    sa.Column('value', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['game_server_config_id'], ['manman.game_server_configs.game_server_config_id'], ),
    sa.PrimaryKeyConstraint('game_server_config_option_id'),
    schema='manman'
    )
    op.create_index('ix_game_server_config_options_config_order', 'game_server_config_options', ['game_server_config_id', 'order', 'option_type'], unique=False, schema='manman')
    op.create_index(op.f('ix_manman_game_server_config_options_game_server_config_id'), 'game_server_config_options', ['game_server_config_id'], unique=False, schema='manman')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_manman_game_server_config_options_game_server_config_id'), table_name='game_server_config_options', schema='manman')
    op.drop_index('ix_game_server_config_options_config_order', table_name='game_server_config_options', schema='manman')
    op.drop_table('game_server_config_options', schema='manman')
    op.drop_index('ixu_game_server_config_commands_config_command', table_name='game_server_config_commands', schema='manman')
    op.drop_index(op.f('ix_manman_game_server_config_commands_game_server_config_id'), table_name='game_server_config_commands', schema='manman')
    op.drop_index(op.f('ix_manman_game_server_config_commands_game_server_command_id'), table_name='game_server_config_commands', schema='manman')
    op.drop_table('game_server_config_commands', schema='manman')
    op.drop_index(op.f('ix_manman_game_server_command_defaults_game_server_command_id'), table_name='game_server_command_defaults', schema='manman')
    op.drop_table('game_server_command_defaults', schema='manman')
    op.drop_index('ixu_game_server_commands_game_server_name', table_name='game_server_commands', schema='manman')
    op.drop_index(op.f('ix_manman_game_server_commands_game_server_id'), table_name='game_server_commands', schema='manman')
    op.drop_table('game_server_commands', schema='manman')
    # ### end Alembic commands ###
