{{/*
Multi-app service template
Generates services for all enabled apps that have a port configured
*/}}
{{- $domain := .Values.domain }}
{{- range $appName, $appConfig := index .Values $domain "apps" }}
{{- if and $appConfig.enabled $appConfig.port }}
{{- $appContext := dict "Values" $.Values "Chart" $.Chart "Release" $.Release "appName" $appName }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "multiapp.fullname" $appContext }}
  labels:
    {{- include "multiapp.appLabels" $appContext | nindent 4 }}
  {{- if $appConfig.service.annotations }}
  annotations:
    {{- toYaml $appConfig.service.annotations | nindent 4 }}
  {{- end }}
spec:
  type: {{ $appConfig.service.type | default "ClusterIP" }}
  ports:
  - port: {{ $appConfig.service.port | default 80 }}
    targetPort: http
    protocol: TCP
    name: http
  {{- if $appConfig.service.additionalPorts }}
  {{- toYaml $appConfig.service.additionalPorts | nindent 2 }}
  {{- end }}
  selector:
    {{- include "multiapp.selectorLabels" $appContext | nindent 4 }}
  {{- if eq ($appConfig.service.type | default "ClusterIP") "LoadBalancer" }}
  {{- if $appConfig.service.loadBalancerIP }}
  loadBalancerIP: {{ $appConfig.service.loadBalancerIP }}
  {{- end }}
  {{- if $appConfig.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
    {{- toYaml $appConfig.service.loadBalancerSourceRanges | nindent 4 }}
  {{- end }}
  {{- end }}
{{- end }}
{{- end }}