"""Build file for the Arduino ESP32 libs archive (@arduino_esp32_libs).

Version: 3.3.7 (ESP-IDF v5.5.2).

Structure of esp32-libs/:
  include/   — ESP-IDF SDK headers (nested component tree; see _SDK_INCLUDES)
  lib/*.a    — precompiled ESP-IDF SDK static libraries
  ld/*.ld    — linker scripts (memory.ld, sections.ld, esp32.rom.*.ld, …)
  bin/       — bootloader ELF files (bootloader_dio_80m.elf, bootloader_qio_80m.elf, …)
  flags/     — text files with the exact build flags Arduino uses

_SDK_INCLUDES is derived verbatim from flags/includes in the archive:
  each '-iwithprefixbefore <path>' entry becomes '"include/<path>"'.
Bootloader conversion (ELF → BIN) is handled by genrules in
//tools/firmware/esp32:BUILD.bazel, which has access to esptool_wrapper.
"""

package(default_visibility = ["//visibility:public"])

# ── Linker scripts ────────────────────────────────────────────────────────────
# Exported so $(execpath @arduino_esp32_libs//:ld/memory.ld) works in
# additional_linker_inputs within esp32.bzl.

exports_files(glob(["ld/*.ld"]))

# ── Bootloader ELF files ──────────────────────────────────────────────────────
# Exposed as filegroups; //tools/firmware/esp32:BUILD.bazel converts them to
# flashable .bin files via esptool elf2image genrules.

filegroup(
    name = "bootloader_elf_dio_80m",
    srcs = ["bin/bootloader_dio_80m.elf"],
)

filegroup(
    name = "bootloader_elf_qio_80m",
    srcs = ["bin/bootloader_qio_80m.elf"],
)

# ── SDK include paths ─────────────────────────────────────────────────────────
# Derived verbatim from esp32-libs/flags/includes (Arduino ESP32 3.3.7).
# Each '-iwithprefixbefore <path>' maps to '"include/<path>"' here.
# Do not edit manually — regenerate from flags/includes if the libs version changes.

_SDK_INCLUDES = [
    # sdkconfig.h is flash-mode-specific; this uses the DIO variant.
    # To support QIO, define a separate sdk_lib_qio target using qio_qspi/ instead.
    "dio_qspi/include",
    "include/newlib/platform_include",
    "include/freertos/config/include",
    "include/freertos/config/include/freertos",
    "include/freertos/config/xtensa/include",
    "include/freertos/FreeRTOS-Kernel/include",
    "include/freertos/FreeRTOS-Kernel/portable/xtensa/include",
    "include/freertos/FreeRTOS-Kernel/portable/xtensa/include/freertos",
    "include/freertos/esp_additions/include",
    "include/esp_hw_support/include",
    "include/esp_hw_support/include/soc",
    "include/esp_hw_support/include/soc/esp32",
    "include/esp_hw_support/dma/include",
    "include/esp_hw_support/ldo/include",
    "include/esp_hw_support/debug_probe/include",
    "include/esp_hw_support/mspi_timing_tuning/include",
    "include/esp_hw_support/mspi_timing_tuning/tuning_scheme_impl/include",
    "include/esp_hw_support/power_supply/include",
    "include/esp_hw_support/port/esp32",
    "include/esp_hw_support/port/esp32/include",
    "include/heap/include",
    "include/heap/tlsf",
    "include/log/include",
    "include/soc/include",
    "include/soc/esp32",
    "include/soc/esp32/include",
    "include/soc/esp32/register",
    "include/hal/platform_port/include",
    "include/hal/esp32/include",
    "include/hal/include",
    "include/esp_rom/include",
    "include/esp_rom/esp32/include",
    "include/esp_rom/esp32/include/esp32",
    "include/esp_rom/esp32",
    "include/esp_common/include",
    "include/esp_system/include",
    "include/esp_system/port/soc",
    "include/esp_system/port/include/private",
    "include/xtensa/esp32/include",
    "include/xtensa/include",
    "include/xtensa/deprecated_include",
    "include/esp_timer/include",
    "include/lwip/include",
    "include/lwip/include/apps",
    "include/lwip/include/apps/sntp",
    "include/lwip/lwip/src/include",
    "include/lwip/port/include",
    "include/lwip/port/freertos/include",
    "include/lwip/port/esp32xx/include",
    "include/lwip/port/esp32xx/include/arch",
    "include/lwip/port/esp32xx/include/sys",
    "include/espressif__esp-tflite-micro",
    "include/espressif__esp-tflite-micro/third_party/gemmlowp",
    "include/espressif__esp-tflite-micro/third_party/flatbuffers/include",
    "include/espressif__esp-tflite-micro/third_party/ruy",
    "include/espressif__esp-tflite-micro/third_party/kissfft",
    "include/espressif__esp32-camera/driver/include",
    "include/espressif__esp32-camera/conversions/include",
    "include/driver/deprecated",
    "include/driver/i2c/include",
    "include/driver/touch_sensor/include",
    "include/driver/twai/include",
    "include/driver/touch_sensor/esp32/include",
    "include/esp_pm/include",
    "include/esp_ringbuf/include",
    "include/esp_driver_gpio/include",
    "include/esp_driver_pcnt/include",
    "include/esp_driver_gptimer/include",
    "include/esp_driver_spi/include",
    "include/esp_driver_mcpwm/include",
    "include/esp_driver_ana_cmpr/include",
    "include/esp_driver_i2s/include",
    "include/esp_driver_sdmmc/include",
    "include/sdmmc/include",
    "include/esp_driver_sdspi/include",
    "include/esp_driver_sdio/include",
    "include/esp_driver_dac/include",
    "include/esp_driver_rmt/include",
    "include/esp_driver_tsens/include",
    "include/esp_driver_sdm/include",
    "include/esp_driver_i2c/include",
    "include/esp_driver_uart/include",
    "include/vfs/include",
    "include/esp_driver_ledc/include",
    "include/esp_driver_parlio/include",
    "include/esp_driver_usb_serial_jtag/include",
    "include/esp_driver_twai/include",
    "include/espressif__esp_jpeg/include",
    "include/espressif__esp_matter/connectedhomeip/connectedhomeip/src",
    "include/espressif__esp_matter/connectedhomeip/connectedhomeip/src/app/ember_coupling",
    "include/espressif__esp_matter/connectedhomeip/connectedhomeip/src/include",
    "include/espressif__esp_matter/connectedhomeip/connectedhomeip/src/lib",
    "include/espressif__esp_matter/connectedhomeip/connectedhomeip/src/lib/dnssd",
    "include/espressif__esp_matter/connectedhomeip/connectedhomeip/src/platform/OpenThread",
    "include/espressif__esp_matter/connectedhomeip/connectedhomeip/third_party/jsoncpp/repo/include",
    "include/espressif__esp_matter/connectedhomeip/connectedhomeip/third_party/nlfaultinjection/include",
    "include/espressif__esp_matter/connectedhomeip/connectedhomeip/third_party/nlassert/repo/include",
    "include/espressif__esp_matter/connectedhomeip/connectedhomeip/third_party/nlio/repo/include",
    "include/espressif__esp_matter/connectedhomeip/connectedhomeip/zzz_generated/app-common",
    "include/esp-idf/espressif__esp_matter",
    "include/esp_matter/zap_common",
    "include/esp_matter",
    "include/esp_matter/utils",
    "include/esp_matter_bridge",
    "include/esp_matter_console",
    "include/espressif__esp_matter/connectedhomeip/connectedhomeip/src/platform/ESP32",
    "include/espressif__esp_matter/connectedhomeip/connectedhomeip/src/platform/ESP32/bluedroid",
    "include/espressif__esp_matter/connectedhomeip/connectedhomeip/src/platform/ESP32/nimble",
    "include/espressif__esp_matter/connectedhomeip/connectedhomeip/src/platform/ESP32/route_hook",
    "include/esp_eth/include",
    "include/esp_event/include",
    "include/bt/include/esp32/include",
    "include/bt/common/osi/include",
    "include/bt/common/api/include/api",
    "include/bt/common/btc/profile/esp/blufi/include",
    "include/bt/common/btc/profile/esp/include",
    "include/bt/common/hci_log/include",
    "include/bt/common/ble_log/include",
    "include/bt/host/bluedroid/api/include/api",
    "include/bt/esp_ble_mesh/common/include",
    "include/bt/esp_ble_mesh/core",
    "include/bt/esp_ble_mesh/core/include",
    "include/bt/esp_ble_mesh/core/storage",
    "include/bt/esp_ble_mesh/btc/include",
    "include/bt/esp_ble_mesh/models/common/include",
    "include/bt/esp_ble_mesh/models/client/include",
    "include/bt/esp_ble_mesh/models/server/include",
    "include/bt/esp_ble_mesh/api/core/include",
    "include/bt/esp_ble_mesh/api/models/include",
    "include/bt/esp_ble_mesh/api",
    "include/bt/esp_ble_mesh/lib/include",
    "include/bt/esp_ble_mesh/v1.1/api/core/include",
    "include/bt/esp_ble_mesh/v1.1/api/models/include",
    "include/bt/esp_ble_mesh/v1.1/btc/include",
    "include/bt/esp_ble_mesh/v1.1/include",
    "include/bt/esp_ble_mesh/v1.1/dfu",
    "include/bt/esp_ble_mesh/v1.1/mbt",
    "include/bt/common/tinycrypt/include",
    "include/bt/common/tinycrypt/port",
    "include/esp_wifi/include",
    "include/esp_wifi/include/local",
    "include/esp_wifi/wifi_apps/include",
    "include/esp_wifi/wifi_apps/nan_app/include",
    "include/esp_phy/include",
    "include/esp_phy/esp32/include",
    "include/esp_netif/include",
    "include/mbedtls/port/include",
    "include/mbedtls/mbedtls/include",
    "include/mbedtls/mbedtls/library",
    "include/mbedtls/esp_crt_bundle/include",
    "include/mbedtls/mbedtls/3rdparty/everest/include",
    "include/mbedtls/mbedtls/3rdparty/p256-m",
    "include/mbedtls/mbedtls/3rdparty/p256-m/p256-m",
    "include/fatfs/diskio",
    "include/fatfs/src",
    "include/fatfs/vfs",
    "include/wear_levelling/include",
    "include/esp_partition/include",
    "include/app_update/include",
    "include/bootloader_support/include",
    "include/bootloader_support/bootloader_flash/include",
    "include/esp_app_format/include",
    "include/esp_bootloader_format/include",
    "include/console",
    "include/esp_vfs_console/include",
    "include/openthread/include",
    "include/openthread/openthread/include",
    "include/nvs_flash/include",
    "include/spi_flash/include",
    "include/espressif__esp_secure_cert_mgr/include",
    "include/espressif__json_parser/include",
    "include/espressif__jsmn/include",
    "include/spiffs/include",
    "include/esp_http_client/include",
    "include/espressif__json_generator/include",
    "include/json/cJSON",
    "include/espressif__mdns/include",
    "include/espressif__esp_delta_ota/include",
    "include/espressif__esp_encrypted_img/include",
    "include/espressif__esp_insights/include",
    "include/espressif__esp_diagnostics/include",
    "include/efuse/include",
    "include/efuse/esp32/include",
    "include/esp_mm/include",
    "include/esp_security/include",
    "include/pthread/include",
    "include/esp_psram/include",
    "include/app_trace/include",
    "include/wpa_supplicant/include",
    "include/wpa_supplicant/port/include",
    "include/wpa_supplicant/esp_supplicant/include",
    "include/esp_coex/include",
    "include/esp_gdbstub/include",
    "include/unity/include",
    "include/unity/unity/src",
    "include/cmock/CMock/src",
    "include/esp_driver_bitscrambler/include",
    "include/http_parser",
    "include/esp-tls",
    "include/esp-tls/esp-tls-crypto",
    "include/esp_adc/include",
    "include/esp_adc/interface",
    "include/esp_adc/esp32/include",
    "include/esp_adc/deprecated/include",
    "include/esp_driver_isp/include",
    "include/esp_driver_cam/include",
    "include/esp_driver_cam/interface",
    "include/esp_driver_jpeg/include",
    "include/esp_driver_ppa/include",
    "include/esp_driver_touch_sens/include",
    "include/esp_driver_touch_sens/hw_ver1/include",
    "include/esp_hal_ieee802154/include",
    "include/esp_hid/include",
    "include/tcp_transport/include",
    "include/esp_http_server/include",
    "include/esp_https_ota/include",
    "include/esp_https_server/include",
    "include/esp_lcd/include",
    "include/esp_lcd/interface",
    "include/protobuf-c/protobuf-c",
    "include/protocomm/include/common",
    "include/protocomm/include/security",
    "include/protocomm/include/transports",
    "include/protocomm/include/crypto/srp6a",
    "include/protocomm/proto-c",
    "include/esp_local_ctrl/include",
    "include/espcoredump/include",
    "include/espcoredump/include/port/xtensa",
    "include/idf_test/include",
    "include/idf_test/include/esp32",
    "include/ieee802154/include",
    "include/mqtt/esp-mqtt/include",
    "include/nvs_sec_provider/include",
    "include/perfmon/include",
    "include/rt/include",
    "include/ulp/ulp_common/include",
    "include/ulp/ulp_fsm/include",
    "include/ulp/ulp_fsm/include/esp32",
    "include/wifi_provisioning/include",
    "include/espressif__esp-nn/include",
    "include/espressif__esp-nn/src/common",
    "include/espressif__rmaker_common/include",
    "include/espressif__cbor/tinycbor/src",
    "include/espressif__esp_diag_data_store/src/rtc_store",
    "include/espressif__esp_diag_data_store/include",
    "include/espressif__esp-serial-flasher/include",
    "include/espressif__esp-serial-flasher/port",
    "include/espressif__esp_rcp_update/include",
    "include/chmorgan__esp-libhelix-mp3/libhelix-mp3/pub",
    "include/espressif__esp-modbus/freemodbus/common/include",
    "include/espressif__esp-zboss-lib/include",
    "include/espressif__esp-zigbee-lib/include",
    "include/espressif__esp-zigbee-lib/include/radio_spinel",
    "include/espressif__libsodium/libsodium/src/libsodium/include",
    "include/espressif__libsodium/port_include",
    "include/espressif__esp-dsp/modules/dotprod/include",
    "include/espressif__esp-dsp/modules/support/include",
    "include/espressif__esp-dsp/modules/support/mem/include",
    "include/espressif__esp-dsp/modules/windows/include",
    "include/espressif__esp-dsp/modules/windows/hann/include",
    "include/espressif__esp-dsp/modules/windows/blackman/include",
    "include/espressif__esp-dsp/modules/windows/blackman_harris/include",
    "include/espressif__esp-dsp/modules/windows/blackman_nuttall/include",
    "include/espressif__esp-dsp/modules/windows/nuttall/include",
    "include/espressif__esp-dsp/modules/windows/flat_top/include",
    "include/espressif__esp-dsp/modules/iir/include",
    "include/espressif__esp-dsp/modules/fir/include",
    "include/espressif__esp-dsp/modules/math/include",
    "include/espressif__esp-dsp/modules/math/add/include",
    "include/espressif__esp-dsp/modules/math/sub/include",
    "include/espressif__esp-dsp/modules/math/mul/include",
    "include/espressif__esp-dsp/modules/math/addc/include",
    "include/espressif__esp-dsp/modules/math/mulc/include",
    "include/espressif__esp-dsp/modules/math/sqrt/include",
    "include/espressif__esp-dsp/modules/matrix/mul/include",
    "include/espressif__esp-dsp/modules/matrix/add/include",
    "include/espressif__esp-dsp/modules/matrix/addc/include",
    "include/espressif__esp-dsp/modules/matrix/mulc/include",
    "include/espressif__esp-dsp/modules/matrix/sub/include",
    "include/espressif__esp-dsp/modules/matrix/include",
    "include/espressif__esp-dsp/modules/fft/include",
    "include/espressif__esp-dsp/modules/dct/include",
    "include/espressif__esp-dsp/modules/conv/include",
    "include/espressif__esp-dsp/modules/common/include",
    "include/espressif__esp-dsp/modules/matrix/mul/test/include",
    "include/espressif__esp-dsp/modules/kalman/ekf/include",
    "include/espressif__esp-dsp/modules/kalman/ekf_imu13states/include",
    "include/espressif__esp_modem/include",
    "include/espressif__esp_modem/command/include",
    "include/espressif__esp_schedule/include",
    "include/espressif__network_provisioning/include",
    "include/espressif__esp_rainmaker/include",
    "include/espressif__lan86xx_common/include",
    "include/espressif__lan867x/include",
    "include/espressif__qrcode/include",
    "include/joltwallet__littlefs/include",
    "include/fb_gfx/include",
]

# ── Precompiled SDK static libraries ─────────────────────────────────────────
# cc_library so Bazel wraps them in --start-group/--end-group (see
# cc_toolchain_config.bzl libraries_to_link_feature).  Matches what
# Arduino's platform.txt does: link all SDK .a files in one group.

# ── SDK defines ───────────────────────────────────────────────────────────────
# Subset of flags/defines required for Arduino core compilation.
# Full list is in esp32-libs/flags/defines; this covers the essential ones.
# ESP_PLATFORM is critical: FreeRTOS.h gates ESP-IDF trace macros on it.
_SDK_DEFINES = [
    "ESP_PLATFORM",
    "IDF_VER=\\\"v5.5.2\\\"",
    "_GNU_SOURCE",
    "MBEDTLS_CONFIG_FILE=\\\"mbedtls/esp_config.h\\\"",
    "UNITY_INCLUDE_CONFIG_H",
    "_GLIBCXX_HAVE_POSIX_SEMAPHORE",
    "_GLIBCXX_USE_POSIX_SEMAPHORE",
    "_POSIX_READER_WRITER_LOCKS",
]

cc_library(
    name = "sdk_lib",
    srcs = glob(["lib/*.a"]) + [
        # Flash-mode-specific libspi_flash.a — provides spi_flash_mmap,
        # esp_mspi_pin_init, and other flash driver symbols.
        "dio_qspi/libspi_flash.a",
    ],
    hdrs = glob([
        "include/**/*.h",
        "dio_qspi/include/*.h",
    ]),
    defines = _SDK_DEFINES,
    includes = _SDK_INCLUDES,
    target_compatible_with = [
        "@platforms//os:none",
        "@@//tools/firmware:cpu_xtensa",
    ],
)
