"""ESP32 flash configurations (board-agnostic flash params for Xtensa ESP32).

Import the appropriate struct in your board's BUILD.bazel and pass it to
flash_firmware() via tools/bazel/esp32.bzl's esp32_firmware() macro.
"""

# Flash config for DIO 80 MHz, 4 MB flash — suitable for most ESP32 dev boards
# including ELEGOO, HiLetgo NodeMCU-32S, DOIT DevKit v1.
ESP32_DIO_80M = struct(
    tool = "esptool",
    chip = "esp32",
    baud = 921600,
    before = "default-reset",
    after = "hard-reset",
    write_flash_args = "--flash-mode dio --flash-freq 80m --flash-size 4MB",
    app_offset = "0x10000",
    # Runfile-root-relative paths for segments flashed before the app binary.
    # bootloader_dio_80m.bin is generated by //tools/firmware/esp32:bootloader_dio_80m_bin
    # (esptool elf2image from the ELF shipped in arduino_esp32_libs).
    pre_segments = [
        ("0x1000", "_main/tools/firmware/esp32/bootloader_dio_80m.bin"),
        ("0x8000", "arduino_esp32/tools/partitions/default.bin"),
    ],
    # Labels for those same files — needed as data deps in the sh_binary.
    pre_segment_labels = [
        "//tools/firmware/esp32:bootloader_dio_80m_bin",
        "@arduino_esp32//:partitions",
    ],
    # Label of the esptool py_binary.
    esptool = "//tools/firmware/esp32:esptool_wrapper",
    esptool_runfile = "_main/tools/firmware/esp32/esptool_wrapper",
)

# QIO 80 MHz variant — faster but requires all 4 data pins; use for modules
# with full quad-IO support (e.g. ESP-WROOM-32).
ESP32_QIO_80M = struct(
    tool = "esptool",
    chip = "esp32",
    baud = 921600,
    before = "default-reset",
    after = "hard-reset",
    write_flash_args = "--flash-mode qio --flash-freq 80m --flash-size 4MB",
    app_offset = "0x10000",
    pre_segments = [
        ("0x1000", "_main/tools/firmware/esp32/bootloader_qio_80m.bin"),
        ("0x8000", "arduino_esp32/tools/partitions/default.bin"),
    ],
    pre_segment_labels = [
        "//tools/firmware/esp32:bootloader_qio_80m_bin",
        "@arduino_esp32//:partitions",
    ],
    esptool = "//tools/firmware/esp32:esptool_wrapper",
    esptool_runfile = "_main/tools/firmware/esp32/esptool_wrapper",
)
