apiVersion: batch/v1
kind: Job
metadata:
  name: manman-migrations
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"  
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  template:
    metadata:
      name: manman-migrations
    spec:
      containers:
      - name: migrations
        image: "{{ .Values.migrations.image }}:{{ .Values.migrations.tag | default .Chart.AppVersion }}"
        command: 
          - python
          - -m
          - alembic  
          - upgrade
          - head
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: manman-database-secret
              key: url
        - name: PYTHONPATH
          value: "/app"
      restartPolicy: OnFailure
      backoffLimit: 3