"""DAL (Data Access Layer) module for database operations.

This module provides organized data access functions grouped by model.
All functions are exposed here for backward compatibility.
"""

# Import all functions from submodules for backward compatibility
from .genai_dal import (
    get_genai_text_by_id,
    get_genai_texts,
    get_genai_texts_by_slack_channel,
    insert_genai_text,
    update_genai_text_response,
)
from .music_poll_dal import (
    MusicPollChannel,
    delete_music_poll,
    delete_music_poll_instance,
    delete_music_poll_response,
    get_music_poll_by_id,
    get_music_poll_channels,
    get_music_poll_instance_by_id,
    get_music_poll_instances,
    get_music_poll_response_by_id,
    get_music_poll_responses,
    get_music_polls,
    get_recent_music_poll_instances,
    get_unprocessed_music_poll_instances,
    insert_music_poll,
    insert_music_poll_instance,
    insert_music_poll_response,
    insert_music_poll_responses,
    update_music_poll,
    update_music_poll_instance,
    update_music_poll_response,
)
from .music_poll_selection import (
    SelectedOption,
    SongCandidate,
    SongSubmission,
    select_poll_options,
    select_scheduled_poll_options,
    song_identity,
)
from .poll_dal import (
    PollSnapshot,
    VoteOutcome,
    cast_poll_vote,
    close_poll,
    create_poll,
    get_poll_snapshot,
    set_poll_message,
)
from .shitposter_dal import (
    GateResult,
    is_channel_opted_in,
    is_shitposter_enabled,
    list_channel_opt_in_history,
    list_kill_switch_history,
    list_opted_in_channel_slack_ids,
    set_channel_opt_in,
    set_kill_switch,
    count_suggestions_by_submitter_since,
    create_suggestion,
    expire_pending_suggestions,
    get_suggestion_by_channel_ts,
    list_submitted_at_since,
    set_state_change_notifier,
    shitposter_gate,
)
from .slack_reaction_dal import (
    add_reaction,
    list_active_reactions,
    normalize_emoji,
    reconcile_message_reactions,
    remove_reaction,
)
from .slack_dal import (
    find_poll_instance_messages,
    get_agent_link_for_channel,
    get_bot_slack_user_slack_ids,
    get_music_poll_channel_slack_ids,
    get_slack_channel,
    get_slack_command_by_id,
    get_slack_message_from_id,
    get_slack_special_channel_type_from_name,
    get_slack_special_channels_from_type,
    get_slack_team_id_map,
    get_slack_teams,
    get_thread_session,
    get_user_teams_from_messages,
    insert_message,
    insert_slack_command,
    insert_thread_session,
    select_distinct_slack_team_slack_id_from_slack_message,
    update_slack_command,
    update_thread_session_status,
    upsert_message,
    upsert_slack_team,
    upsert_slack_teams,
    upsert_slack_users,
    upsert_slack_users_activity,
)
from .task_dal import (
    get_last_successful_task_instance,
    insert_task_instances,
    upsert_task,
    upsert_tasks,
)

__all__ = [
    # Slack reactions
    "add_reaction",
    "remove_reaction",
    "list_active_reactions",
    "normalize_emoji",
    # Slack functions
    "get_music_poll_channel_slack_ids",
    "get_bot_slack_user_slack_ids",
    "insert_message",
    "upsert_message",
    "select_distinct_slack_team_slack_id_from_slack_message",
    "upsert_slack_teams",
    "upsert_slack_team",
    "get_slack_teams",
    "get_slack_team_id_map",
    "get_user_teams_from_messages",
    "upsert_slack_users",
    "upsert_slack_users_activity",
    "get_slack_channel",
    "find_poll_instance_messages",
    "insert_slack_command",
    "get_slack_command_by_id",
    "update_slack_command",
    "get_slack_special_channel_type_from_name",
    "get_slack_special_channels_from_type",
    "get_slack_message_from_id",
    # whagent-net channel/thread link functions
    "get_agent_link_for_channel",
    "get_thread_session",
    "insert_thread_session",
    "update_thread_session_status",
    # Task functions
    "upsert_tasks",
    "upsert_task",
    "insert_task_instances",
    "get_last_successful_task_instance",
    # GenAI functions
    "insert_genai_text",
    "get_genai_texts",
    "get_genai_texts_by_slack_channel",
    "get_genai_text_by_id",
    "update_genai_text_response",
    # Music Poll functions
    "MusicPollChannel",
    "insert_music_poll",
    "get_music_poll_by_id",
    "get_music_poll_channels",
    "get_music_polls",
    "update_music_poll",
    "delete_music_poll",
    "insert_music_poll_instance",
    "get_music_poll_instance_by_id",
    "get_music_poll_instances",
    "get_unprocessed_music_poll_instances",
    "get_recent_music_poll_instances",
    "update_music_poll_instance",
    "delete_music_poll_instance",
    "insert_music_poll_responses",
    "insert_music_poll_response",
    "get_music_poll_response_by_id",
    "get_music_poll_responses",
    "update_music_poll_response",
    "delete_music_poll_response",
    # Weekly music-poll selection
    "SelectedOption",
    "SongCandidate",
    "SongSubmission",
    "select_poll_options",
    "select_scheduled_poll_options",
    "song_identity",
    # Poll functions
    "PollSnapshot",
    "VoteOutcome",
    "create_poll",
    "set_poll_message",
    "get_poll_snapshot",
    "cast_poll_vote",
    "close_poll",
]
