load("@rules_go//go:def.bzl", "go_binary", "go_library")

go_library(
    name = "bridge_lib",
    srcs = [
        "main.go",
        "session.go",
    ],
    importpath = "github.com/whale-net/everything/tools/pi_console/bridge",
    visibility = ["//visibility:private"],
)

go_binary(
    name = "bridge",
    embed = [":bridge_lib"],
    visibility = ["//visibility:public"],
)
