load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "htmxsse",
    srcs = [
        "doc.go",
        "hub.go",
    ],
    importpath = "github.com/whale-net/everything/libs/go/htmxsse",
    visibility = ["//visibility:public"],
    deps = [
        "//libs/go/rmq",
    ],
)

go_test(
    name = "htmxsse_test",
    srcs = ["hub_test.go"],
    embed = [":htmxsse"],
    deps = [
        "@com_github_stretchr_testify//assert",
        "@com_github_stretchr_testify//require",
    ],
)
