load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "htmxsse",
    srcs = [
        "attach.go",
        "doc.go",
        "handler.go",
        "hub.go",
    ],
    importpath = "github.com/whale-net/everything/libs/go/htmxsse",
    visibility = ["//visibility:public"],
    deps = [
        "//libs/go/rmq",
    ],
)

go_test(
    name = "htmxsse_test",
    srcs = [
        "handler_test.go",
        "hub_test.go",
    ],
    embed = [":htmxsse"],
    deps = [
        "//libs/go/rmq",
        "@com_github_rabbitmq_amqp091_go//:amqp091-go",
        "@com_github_stretchr_testify//assert",
        "@com_github_stretchr_testify//require",
    ],
)
