name: 'Setup Go Module Cache'
description: 'Sets up Go module caching with optimized cache key handling for missing go.sum files'
branding:
  icon: 'package'
  color: 'blue'

inputs:
  go-version:
    description: 'Go version to install'
    required: true
    default: '1.25'
  cache-dependency-path:
    description: 'Used to specify the path to a dependency file - go.mod'
    required: false
    default: 'go.mod'
  cache-key-suffix:
    description: 'Additional suffix for cache key customization'
    required: false
    default: ''

outputs:
  cache-hit:
    description: 'A boolean value to indicate if a cache was hit'
    value: ${{ steps.go-cache.outputs.cache-hit }}
  go-version:
    description: 'The installed Go version'
    value: ${{ steps.setup-go.outputs.go-version }}

runs:
  using: composite
  steps:
    - name: Setup Go
      id: setup-go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ inputs.go-version }}
        
    - name: Setup Go module cache
      id: go-cache
      uses: actions/cache@v4
      with:
        path: |
          ~/go/pkg/mod
          ~/.cache/go-build
        # Use separate hashFiles calls to handle missing go.sum gracefully
        # This prevents "Dependencies file is not found" errors when go.sum doesn't exist
        key: ${{ runner.os }}-go-${{ hashFiles(inputs.cache-dependency-path) }}-${{ hashFiles('go.sum') }}${{ inputs.cache-key-suffix }}
        restore-keys: |
          ${{ runner.os }}-go-${{ hashFiles(inputs.cache-dependency-path) }}-
          ${{ runner.os }}-go-