name: CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Setup Bazelisk
      uses: bazelbuild/setup-bazelisk@v3
      
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'
        
    - name: Mount Bazel cache
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/bazel
          ~/.cache/bazelisk
        key: ${{ runner.os }}-bazel-${{ hashFiles('**/BUILD.bazel', '**/*.bzl', 'MODULE.bazel', 'go.mod', 'requirements.lock.txt') }}
        restore-keys: |
          ${{ runner.os }}-bazel-
          
    - name: Run tests
      run: |
        # Bazel automatically handles incremental testing
        # Only rebuilds and retests what's affected by changes
        bazel test --config=ci //...
        
    - name: Build applications
      run: |
        bazel build //hello_python:hello_python //hello_go:hello_go
        
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: bazel-testlogs/
        retention-days: 7
