name: CI

on: [push, pull_request]

jobs:
  python-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install uv
      run: curl -LsSf https://astral.sh/uv/install.sh | sh
    - name: Create and activate virtual environment
      run: uv venv
    - name: Install dependencies
      run: ./.venv/bin/uv pip install -r requirements.txt
    - name: Run Python tests
      run: ./.venv/bin/pytest examples/api-py/tests/test_api.py

  go-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'
    - name: Run Go tests
      run: |
        go test ./examples/api-go/...
        go test ./examples/headless-go/...
        go test ./examples/pubsub-go/...
        go test ./examples/temporal-go/...
