name: CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  # Plan test execution - determine which tests need running
  plan-tests:
    name: Plan Test Execution
    runs-on: ubuntu-latest
    outputs:
      test_targets: ${{ steps.plan.outputs.test_targets }}
      needs_testing: ${{ steps.plan.outputs.needs_testing }}
      test_count: ${{ steps.plan.outputs.test_count }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Setup Build Environment
      uses: ./.github/actions/setup-build-env
      with:
        cache-suffix: 'plan-tests'
        bazel-remote-cache-url: ${{ secrets.BAZEL_REMOTE_CACHE_URL }}
        bazel-remote-cache-user: ${{ secrets.BAZEL_REMOTE_CACHE_USER }}
        bazel-remote-cache-password: ${{ secrets.BAZEL_REMOTE_CACHE_PASSWORD }}
        
    - name: Plan test execution using release tool
      id: plan
      run: |
        # Determine which tests to run based on changes
        if [ "${{ github.event_name }}" = "pull_request" ]; then
          # For PRs, compare against the base branch
          BASE_COMMIT="${{ github.event.pull_request.base.sha }}"
          echo "PR detected: comparing against base commit $BASE_COMMIT"
        elif [ "${{ github.event_name }}" = "push" ] && [ -n "${{ github.event.before }}" ]; then
          # For pushes, compare against the previous commit
          BASE_COMMIT="${{ github.event.before }}"
          echo "Push detected: comparing against previous commit $BASE_COMMIT"
        else:
          # Fallback: test all
          echo "Cannot determine base commit, will test all tests"
          BASE_COMMIT=""
        fi
        
        # Use release tool to plan test execution with rdeps-based change detection
        echo "Planning test execution using Bazel rdeps..."
        if [ -n "$BASE_COMMIT" ]; then
          PLAN_OUTPUT=$(bazel run //tools:release -- plan-tests \
            --base-commit="$BASE_COMMIT" \
            --format github)
        else
          # No base commit - output will indicate all tests need running
          PLAN_OUTPUT=$(bazel run //tools:release -- plan-tests --format github)
        fi
        
        # Parse output and set GitHub outputs
        echo "$PLAN_OUTPUT" | while IFS= read -r line; do
          if [[ "$line" == test_targets=* ]] || [[ "$line" == needs_testing=* ]] || [[ "$line" == test_count=* ]]; then
            echo "$line" >> $GITHUB_OUTPUT
          fi
        done
        
        # Show what we're planning to test
        TEST_TARGETS=$(echo "$PLAN_OUTPUT" | grep "^test_targets=" | cut -d= -f2)
        NEEDS_TESTING=$(echo "$PLAN_OUTPUT" | grep "^needs_testing=" | cut -d= -f2)
        TEST_COUNT=$(echo "$PLAN_OUTPUT" | grep "^test_count=" | cut -d= -f2)
        
        if [[ "$NEEDS_TESTING" == "true" ]]; then
          echo "Will run $TEST_COUNT test target(s)"
        else
          echo "No tests need to run"
        fi

  # Test job - runs affected tests only
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: plan-tests
    if: needs.plan-tests.outputs.needs_testing == 'true'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Setup Build Environment
      uses: ./.github/actions/setup-build-env
      with:
        cache-suffix: 'test'
        bazel-remote-cache-url: ${{ secrets.BAZEL_REMOTE_CACHE_URL }}
        bazel-remote-cache-user: ${{ secrets.BAZEL_REMOTE_CACHE_USER }}
        bazel-remote-cache-password: ${{ secrets.BAZEL_REMOTE_CACHE_PASSWORD }}
        
    - name: Run affected tests
      run: |
        # Run only the affected tests (or all if no specific targets)
        TEST_TARGETS="${{ needs.plan-tests.outputs.test_targets }}"
        TEST_COUNT="${{ needs.plan-tests.outputs.test_count }}"
        
        if [ -z "$TEST_TARGETS" ]; then
          echo "Running all tests..."
          bazel test //...
        else
          echo "Running $TEST_COUNT affected test target(s)..."
          bazel test $TEST_TARGETS
        fi
        
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: bazel-testlogs/
        retention-days: 7

  # Plan Docker builds - determine which apps need building
  plan-docker:
    name: Plan Docker Builds
    runs-on: ubuntu-latest
    needs: test
    outputs:
      matrix: ${{ steps.plan.outputs.matrix }}
      apps: ${{ steps.plan.outputs.apps }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Setup Build Environment
      uses: ./.github/actions/setup-build-env
      with:
        cache-suffix: 'plan'
        bazel-remote-cache-url: ${{ secrets.BAZEL_REMOTE_CACHE_URL }}
        bazel-remote-cache-user: ${{ secrets.BAZEL_REMOTE_CACHE_USER }}
        bazel-remote-cache-password: ${{ secrets.BAZEL_REMOTE_CACHE_PASSWORD }}
        
    - name: Plan Docker builds using release tool
      id: plan
      env:
        GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}
      run: |
        # Determine what to build based on changes
        if [ "${{ github.event_name }}" = "pull_request" ]; then
          # For PRs, compare against the base branch
          BASE_COMMIT="${{ github.event.pull_request.base.sha }}"
          echo "PR detected: comparing against base commit $BASE_COMMIT"
          EVENT_TYPE="pull_request"
        elif [ "${{ github.event_name }}" = "push" ] && [ -n "${{ github.event.before }}" ]; then
          # For pushes, compare against the previous commit
          BASE_COMMIT="${{ github.event.before }}"
          echo "Push detected: comparing against previous commit $BASE_COMMIT"
          EVENT_TYPE="push"
        else
          # Fallback: build all apps
          echo "Cannot determine base commit, building all apps"
          BASE_COMMIT=""
          EVENT_TYPE="fallback"
        fi
        
        # Use release helper to plan the Docker builds
        echo "Planning Docker builds using release tool..."
        PLAN_OUTPUT=$(bazel run //tools:release -- plan \
          --event-type "$EVENT_TYPE" \
          --base-commit="$BASE_COMMIT" \
          --format github)
        
        # Parse output from release helper and set GitHub outputs
        # Use process substitution to avoid subshell issues with pipes
        while IFS= read -r line; do
          if [[ "$line" == matrix=* ]]; then
            echo "${line}" >> $GITHUB_OUTPUT
          elif [[ "$line" == apps=* ]]; then
            echo "${line}" >> $GITHUB_OUTPUT
            APPS_LIST="${line#apps=}"
            if [[ -n "$APPS_LIST" ]]; then
              echo "Apps to build: $APPS_LIST"
            else
              echo "No apps to build"
            fi
          fi
        done <<< "$PLAN_OUTPUT"

  # Docker job - builds container images using the release tool
  docker:
    name: Build ${{ matrix.app }} Image
    runs-on: ubuntu-latest
    needs: plan-docker
    if: needs.plan-docker.outputs.apps != '' && needs.plan-docker.outputs.apps != null
    strategy:
      matrix: ${{ fromJson(needs.plan-docker.outputs.matrix) }}
      fail-fast: false
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
      
    - name: Setup Build Environment
      uses: ./.github/actions/setup-build-env
      with:
        setup-docker: 'true'
        cache-suffix: 'docker'
        bazel-remote-cache-url: ${{ secrets.BAZEL_REMOTE_CACHE_URL }}
        bazel-remote-cache-user: ${{ secrets.BAZEL_REMOTE_CACHE_USER }}
        bazel-remote-cache-password: ${{ secrets.BAZEL_REMOTE_CACHE_PASSWORD }}
      
    # Log in to GitHub Container Registry using GITHUB_TOKEN
    - name: Log in to GitHub Container Registry
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Build Docker image for ${{ matrix.app }}
      env:
        GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}
        APP: ${{ matrix.app }}
      run: |
        # Build Docker image for the specific app from the matrix
        echo "Building Docker image for $APP using release tool..."
        bazel run //tools:release -- build "$APP"
        
        # Show the built Docker image
        echo "Built Docker image for $APP:"
        docker images | grep -E "(REPOSITORY|$APP)" || docker images | head -5
        
    - name: Push image to registry (main branch only)
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      env:
        GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}
        APP: ${{ matrix.app }}
      run: |
        # Publish the specific app image to registry
        echo "Publishing $APP image to registry..."
        bazel run //tools:release -- release "$APP" --version "latest" --commit "${{ github.sha }}"
        
  # Build summary - collects status of all jobs for branch protection
  build-summary:
    name: Build Summary
    runs-on: ubuntu-latest
    needs: [plan-tests, test, plan-docker, docker]
    if: always()
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Build Environment
      uses: ./.github/actions/setup-build-env
      with:
        cache-suffix: 'summary'
        bazel-remote-cache-url: ${{ secrets.BAZEL_REMOTE_CACHE_URL }}
        bazel-remote-cache-user: ${{ secrets.BAZEL_REMOTE_CACHE_USER }}
        bazel-remote-cache-password: ${{ secrets.BAZEL_REMOTE_CACHE_PASSWORD }}
      
    - name: Collect build results and generate summary
      run: |
        echo "=== CI Build Summary ===" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        
        # Check test results
        TEST_NEEDS="${{ needs.plan-tests.outputs.needs_testing }}"
        TEST_COUNT="${{ needs.plan-tests.outputs.test_count }}"
        TEST_RESULT="${{ needs.test.result }}"
        
        echo "**Testing:**" >> $GITHUB_STEP_SUMMARY
        if [[ "$TEST_NEEDS" == "true" ]]; then
          echo "- Tested $TEST_COUNT affected target(s)" >> $GITHUB_STEP_SUMMARY
          echo "- Status: $TEST_RESULT" >> $GITHUB_STEP_SUMMARY
        else
          echo "- No tests needed (no test targets affected)" >> $GITHUB_STEP_SUMMARY
          echo "- Status: skipped" >> $GITHUB_STEP_SUMMARY
        fi
        echo "" >> $GITHUB_STEP_SUMMARY
        
        # Check if any apps were planned for building
        PLANNED_APPS="${{ needs.plan-docker.outputs.apps }}"
        echo "**Docker Builds:**" >> $GITHUB_STEP_SUMMARY
        if [[ -z "$PLANNED_APPS" || "$PLANNED_APPS" == "null" ]]; then
          echo "- No apps required building" >> $GITHUB_STEP_SUMMARY
          echo "- Status: skipped" >> $GITHUB_STEP_SUMMARY
        else
          echo "- Apps: $PLANNED_APPS" >> $GITHUB_STEP_SUMMARY
          echo "- Status: ${{ needs.docker.result }}" >> $GITHUB_STEP_SUMMARY
        fi
        echo "" >> $GITHUB_STEP_SUMMARY
        
        # Determine overall status
        PLAN_TEST_RESULT="${{ needs.plan-tests.result }}"
        PLAN_DOCKER_RESULT="${{ needs.plan-docker.result }}"
        
        echo "**Overall Status:**" >> $GITHUB_STEP_SUMMARY
        
        # Check if planning succeeded
        if [[ "$PLAN_TEST_RESULT" != "success" ]] || [[ "$PLAN_DOCKER_RESULT" != "success" ]]; then
          echo "❌ **FAILED** - Planning phase failed" >> $GITHUB_STEP_SUMMARY
          echo "::error::CI planning failed"
          exit 1
        fi
        
        # Check if tests succeeded (or were skipped)
        if [[ "$TEST_NEEDS" == "true" ]] && [[ "$TEST_RESULT" != "success" ]]; then
          echo "❌ **FAILED** - Tests failed" >> $GITHUB_STEP_SUMMARY
          echo "::error::Tests failed"
          exit 1
        fi
        
        # Check if Docker builds succeeded (or were skipped)
        DOCKER_RESULT="${{ needs.docker.result }}"
        if [[ -n "$PLANNED_APPS" ]] && [[ "$PLANNED_APPS" != "null" ]] && [[ "$DOCKER_RESULT" != "success" ]] && [[ "$DOCKER_RESULT" != "skipped" ]]; then
          echo "❌ **FAILED** - Docker builds failed" >> $GITHUB_STEP_SUMMARY
          echo "::error::Docker builds failed"
          exit 1
        fi
        
        # All good!
        echo "✅ **PASSED**" >> $GITHUB_STEP_SUMMARY
        echo "All CI checks passed successfully"
        
