name: CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

env:
  # Shared cache key components for consistent caching across jobs
  CACHE_KEY_FILES: '**/BUILD.bazel,**/*.bzl,MODULE.bazel,MODULE.bazel.lock,go.mod,requirements.lock.txt,.bazelrc,.bazelversion'

jobs:
  # Build job - builds applications first
  build:
    name: Build
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Setup Bazelisk
      uses: bazelbuild/setup-bazelisk@v3
      
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.25'  # Match MODULE.bazel version
        
    - name: Setup Go module cache
      uses: actions/cache@v4
      with:
        path: |
          ~/go/pkg/mod
          ~/.cache/go-build
        key: ${{ runner.os }}-go-${{ hashFiles('go.mod', 'go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
        
    - name: Mount Bazel cache
      uses: actions/cache@v4
      with:
        path: |
          /tmp/bazel-cache
          /tmp/bazel-repo-cache
          ~/.cache/bazelisk
        key: ${{ runner.os }}-bazel-${{ hashFiles(env.CACHE_KEY_FILES) }}
        restore-keys: |
          ${{ runner.os }}-bazel-
          
    - name: Configure Bazel and Go caches
      run: |
        # Create Bazel cache directories
        mkdir -p /tmp/bazel-cache /tmp/bazel-repo-cache
        # Initialize Go cache directories using Bazel tool
        bazel run //:init-go-cache
        
    - name: Build applications
      run: |
        # Build all binary targets (not libraries or tests) with CI optimizations
        bazel query "kind('.*_binary', //...)" | xargs bazel build --config=ci
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: |
          bazel-bin/*/
          !bazel-bin/**/runfiles/
          !bazel-bin/**/*.runfiles/
          !bazel-bin/**/*_test*
          !bazel-bin/**/*.so
        retention-days: 3

  # Test job - runs tests after successful build
  test:
    name: Test
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Setup Bazelisk
      uses: bazelbuild/setup-bazelisk@v3
      
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.25'  # Match MODULE.bazel version
        
    - name: Setup Go module cache
      uses: actions/cache@v4
      with:
        path: |
          ~/go/pkg/mod
          ~/.cache/go-build
        key: ${{ runner.os }}-go-${{ hashFiles('go.mod', 'go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
        
    - name: Mount Bazel cache
      uses: actions/cache@v4
      with:
        path: |
          /tmp/bazel-cache
          /tmp/bazel-repo-cache
          ~/.cache/bazelisk
        key: ${{ runner.os }}-bazel-${{ hashFiles(env.CACHE_KEY_FILES) }}
        restore-keys: |
          ${{ runner.os }}-bazel-
          
    - name: Configure Bazel and Go caches
      run: |
        # Create Bazel cache directories
        mkdir -p /tmp/bazel-cache /tmp/bazel-repo-cache
        # Initialize Go cache directories using Bazel tool
        bazel run //:init-go-cache
        
    - name: Run tests
      run: |
        # Bazel automatically handles incremental testing
        # Only rebuilds and retests what's affected by changes
        bazel test --config=ci //...
        
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: bazel-testlogs/
        retention-days: 7

  # Docker job - builds container images using the release tool
  docker:
    name: Build Docker Images
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Bazelisk
      uses: bazelbuild/setup-bazelisk@v3
      
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.25'  # Match MODULE.bazel version
        
    - name: Setup Go module cache
      uses: actions/cache@v4
      with:
        path: |
          ~/go/pkg/mod
          ~/.cache/go-build
        key: ${{ runner.os }}-go-${{ hashFiles('go.mod', 'go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
        
    - name: Mount Bazel cache
      uses: actions/cache@v4
      with:
        path: |
          /tmp/bazel-cache
          /tmp/bazel-repo-cache
          ~/.cache/bazelisk
        key: ${{ runner.os }}-bazel-${{ hashFiles(env.CACHE_KEY_FILES) }}
        restore-keys: |
          ${{ runner.os }}-bazel-
          
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Configure Bazel and Go caches
      run: |
        # Create Bazel cache directories
        mkdir -p /tmp/bazel-cache /tmp/bazel-repo-cache
        # Initialize Go cache directories using Bazel tool
        bazel run //:init-go-cache
      
    # NOTE: GHCR_PAT secret should be created with write:packages and read:packages scopes
    # Falls back to GITHUB_TOKEN if GHCR_PAT is not available (limited permissions)
    - name: Log in to GitHub Container Registry
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_PAT || secrets.GITHUB_TOKEN }}
        
    - name: Build Docker images using release tool
      env:
        GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}
      run: |
        # Use the release tool to build images consistently
        echo "Building Docker images using release tool..."
        
        # Get list of all apps
        APPS=$(bazel run //tools:release -- list)
        echo "Apps to build: $APPS"
        
        # Build images for all apps using the release tool
        for app in $APPS; do
          echo "Building image for $app..."
          bazel run //tools:release -- build "$app"
        done
        
        # Show loaded Docker images
        echo "Built Docker images:"
        docker images
        
    - name: Push images to registry (main branch only)
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      env:
        GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}
      run: |
        # Use the release tool to publish images with latest and commit tags
        echo "Publishing Docker images using release tool..."
        
        # Get list of all apps
        APPS=$(bazel run //tools:release -- list)
        
        # Publish images for all apps using the release tool
        for app in $APPS; do
          echo "Publishing $app with latest and commit tags..."
          bazel run //tools:release -- release "$app" --version "latest" --commit "${{ github.sha }}"
        done
        
    - name: Save Docker images as artifacts (PR builds)
      if: github.event_name == 'pull_request'
      run: |
        # Save images for PR builds
        mkdir -p docker-images
        APPS=$(bazel run //tools:release -- list)
        
        for app in $APPS; do
          echo "Saving image for $app..."
          safe_name="${app}_latest"
          docker save "${app}:latest" | gzip > "docker-images/${safe_name}.tar.gz"
        done
        
    - name: Upload Docker images (PR builds)
      if: github.event_name == 'pull_request'
      uses: actions/upload-artifact@v4
      with:
        name: docker-images
        path: docker-images/
        retention-days: 3
